### PR TITLE
Favicon.ico is not an error.

### LINKED ISSUE #2539: 🥕[Bug]: GraphQL error when navigating to REST endpoint (favicon.ico)
Error occurs also when you navigate to endpoint like `/api/Actor`.

Error occurs also when you navigate to the `/` root.

Image

```
fail: Azure.DataApiBuilder.Service.Controllers.RestController[0]
      f355c82b-7881-4e9f-af4e-739d543d925a Error handling REST request.
      Azure.DataApiBuilder.Service.Exceptions.DataApiBuilderException: GraphQL request redirected to favicon.ico.
         at Azure.DataApiBuilder.Service.Controllers.RestController.HandleOperation(String route, EntityActionOperation operationType) in /_/src/Service/Controllers/RestController.cs:line 192
```

## Problem

```
GraphQL request redirected to favicon.ico.
```

## Reference

https://github.com/Azure/data-api-builder/blob/main/src/Service/Controllers/RestController.cs#L190-L196

### PR DESCRIPTION
**Pull request by JerryNixon**
Closes #2539

Prevents error message in console that is not a real error. 

image

### CODE REVIEW

**Review by rohkhann — DISMISSED** [review]

**Review by Aniruddh25 — DISMISSED** [review]
LGTM, thanks for fixing it in.

File: src/Service/Controllers/RestController.cs [hunk 1]
```diff
@@ -189,10 +189,7 @@ private async Task<IActionResult> HandleOperation(
             {
                 if (route.Equals(REDIRECTED_ROUTE))
                 {
-                    throw new DataApiBuilderException(
-                        message: $"GraphQL request redirected to {REDIRECTED_ROUTE}.",
-                        statusCode: HttpStatusCode.BadRequest,
-                        subStatusCode: DataApiBuilderException.SubStatusCodes.BadRequest);
+                    return default!;
```
Comment (Aniruddh25) [inline src/Service/Controllers/RestController.cs:192]:
```suggestion
                    return NotFound();
```

**Review by Aniruddh25 — DISMISSED** [review]

**Review by Aniruddh25 — APPROVED** [review]

**Review by RubenCerna2079 — APPROVED** [review]
