### PR TITLE
lowercase CLI enum values in HelpText and error messages (Group 3)

### LINKED ISSUE #3445: CLI Incorrect Casing (Group 3)
## Group 3: CLI Incorrect Casing

Tracks 4 bugs where CLI help text and error messages display PascalCase/UPPERCASE enum values instead of the lowercase values required by the JSON schema.

### Child Issues
- [ ] #3361 - host-mode HelpText: Development/Production -> development/production
- [ ] #3362 - rest.methods HelpText: GET/POST -> get/post
- [ ] #3363 - graphql.operation HelpText: Query/Mutation -> query/mutation
- [ ] #3364 - graphql.operation (duplicate of #3363)

### PR
- #3444

### PR DESCRIPTION
**Pull request by souvikghosh04**
## Summary

- Closes on #3445 

Fixes 4 issues where CLI `--help` text and error messages showed PascalCase or UPPERCASE enum values instead of the lowercase values required by the JSON schema.

The JSON serialization layer already produces lowercase (via `EnumMemberJsonEnumConverterFactory`), so these fixes align the CLI display layer to match.

## Issues Addressed

| Issue | Option | CLI Showed | Schema Requires | Fix |
|-------|--------|-----------|-----------------|-----|
| #3361 | `--host-mode` (init) | `Development or Production` | `development or production` | HelpText lowercased |
| #3362 | `--rest.methods` (add/update) | `[GET, POST, PUT, PATCH, DELETE]` | `[get, post, put, patch, delete]` | HelpText lowercased |
| #3363 | `--graphql.operation` (add/update) | `[Query, Mutation]` | `[query, mutation]` | HelpText lowercased |
| #3364 | `--graphql.operation` (add/update) | Same as #3363 | Same as #3363 | Same fix |

## Files Changed

| File | Changes |
|------|---------|
| `src/Cli/Commands/InitOptions.cs` | `host-mode` HelpText: lowercase enum values |
| `src/Cli/Commands/EntityOptions.cs` | `rest.methods` and `graphql.operation` HelpText: lowercase enum values |
| `src/Cli/Utils.cs` | REST method and GraphQL operation error messages: lowercase enum names |

## Testing

- [x] Unit tests

### CODE REVIEW

**Review by Aniruddh25 — APPROVED** [review]

File: src/Cli/Commands/EntityOptions.cs [hunk 1]
```diff
@@ -83,13 +83,13 @@ public EntityOptions(
         [Option("rest", Required = false, HelpText = "Route for rest api.")]
         public string? RestRoute { get; }
 
-        [Option("rest.methods", Required = false, Separator = ',', HelpText = "HTTP actions to be supported for stored procedure. Specify the actions as a comma separated list. Valid HTTP actions are : [GET, POST, PUT, PATCH, DELETE]")]
+        [Option("rest.methods", Required = false, Separator = ',', HelpText = "HTTP actions to be supported for stored procedure. Specify the actions as a comma separated list. Valid HTTP actions are: [get, post, put, patch, delete]")]
```
Comment (RubenCerna2079) [inline src/Cli/Commands/EntityOptions.cs:86]: Even if we change the description to say we use the lowercase version of the values. Both lowercase and uppercase should be supported.
So can you just test it locally to ensure it works for both?

**Review by RubenCerna2079 — APPROVED** [review]
Approving assuming comments will be addressed

File: src/Cli/Commands/EntityOptions.cs (hunk 1 above)
Comment (souvikghosh04) [reply src/Cli/Commands/EntityOptions.cs:86]: This PR only changes the display text (HelpText and error messages) to show lowercase values. The actual parsing was never case-sensitive, so GET, get, Get all work and will continue to work.
