### PR TITLE
Fix mssql filter parser for wildcard characters for `LIKE` query

### LINKED ISSUE #2434: [Bug]: filter endsWith: "_" is incorrectly resolved
### What happened?

I created a query like

```graphql
query Customers{
    customer(
        filter: { id: {endsWith: "_CON" } }
    ) {
        endCursor
        hasNextPage
        items {
            id
        }
    }
}
```

I received an empty json response, although the database contains customers with ids ending like "_CON".

I investigated the SQL queries the database receives and found this.

`WHERE Id LIKE '%\_CON'`

### Version

1.2.11+c7ca8db8558a63919c530e454c8f18b45d5b931c

### What database are you using?

Azure SQL

### What hosting model are you using?

Container Apps, Local (including CLI)

### Which API approach are you accessing DAB through?

GraphQL

### Relevant log output

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by abhishekkumams**
## Why make this change?

- Closes #2434 
  - when wildcard characters are used as literal character in search, filter query fails to resolve correctly.
  -  we never use the wild characters of SQL for their intended use as wild characters when queried from GraphQL. They are always used as literal search characters.

## What is this change?
- we are adding `\` whenever a special character (wildcard) is used in the filter query.
- while mysql,pgsql are able to understand and treat `\` as escape charachters, for MsSQL, we have to use `ESCAPE` clause.
- The `ESCAPE` clause in a `LIKE` query specifies a character to treat as an escape character. This is especially useful when your search pattern contains special characters like %, _, or the actual escape character, which otherwise have special meanings in LIKE patterns.
- I have updated the query builder for MsSql, which checks if it is a `LIKE` query and only then it adds an `ESCAPE` clause.

There is a special case for mysql for wildcard (`\`), which needs to be handled separately. I have created an issue to tackle it. #2499

## How was this tested?

- [X] Integration Tests
- [x] manual tests

## Sample Request(s)
image
image
image

### CODE REVIEW

File: src/Core/Resolvers/MsSqlQueryBuilder.cs [hunk 1]
```diff
@@ -60,9 +61,17 @@ public string Build(SqlQueryStructure structure)
                                     Build(structure.PaginationMetadata.PaginationPredicate));
             }
 
+            // we add '\' carachter to escape the special characters in the string, but if special characters are needed to be searched
```
Comment (Aniruddh25) [inline src/Core/Resolvers/MsSqlQueryBuilder.cs:64]:
```suggestion
            // we add '\' character to escape the special characters in the string, but if special characters are needed to be searched
```

**Review by Aniruddh25 — COMMENTED** [review]
Can you please mention in the PR description that we never use the wild characters of SQL for their intended use as wild characters when queried from GraphQL? They are always used as literal search characters and hence your PR to add the ESCAPE clause makes sense.

File: src/Service.Tests/CosmosTests/QueryFilterTests.cs [hunk 2]
```diff
@@ -407,28 +407,6 @@ public async Task TestStringFiltersNotContains()
...
-        [TestMethod]
-        public async Task TestStringFiltersContainsWithSpecialChars()
-        {
-            string gqlQuery = @"{
-                planets(first: 10, " + QueryBuilder.FILTER_FIELD_NAME + @" : {name: {contains: ""%""}})
-                {
-                    items {
-                        name
-                    }
-                }
```
Comment (Aniruddh25) [inline src/Service.Tests/CosmosTests/QueryFilterTests.cs:424]: Why remove the test altogether? We could keep the test and remove the Ignore clause if its working now.

File: src/Service.Tests/SqlTests/GraphQLFilterTests/MsSqlGQLFilterTests.cs [hunk 3]
```diff
@@ -58,6 +58,62 @@ ORDER BY [__column1] asc
...
+            DisplayName = "endsWith: ']'"
+        )]
+        [DataRow(
+            "{ title: { contains: \"\\\\\" } }",
+            "%\\\\%",
+            DisplayName = "Contains single backslash: '\\' "
+        )]
+        [DataRow(
+            "{ title: { contains: \"\\\\\\\\\" } }",
+            "%\\\\\\\\%",
```
Comment (Aniruddh25) [inline src/Service.Tests/SqlTests/GraphQLFilterTests/MsSqlGQLFilterTests.cs:102]: Also test for `[^a]` since that is one of the wild characters.. See here: https://learn.microsoft.com/en-us/sql/t-sql/language-elements/like-transact-sql?view=sql-server-ver16#pattern

File: src/Service.Tests/CosmosTests/QueryFilterTests.cs (hunk 2 above)
Comment (Aniruddh25) [reply src/Service.Tests/CosmosTests/QueryFilterTests.cs:424]: I dont see any equivalent test added here for CosmosDB similar to how its added for the other Sql types.

**Review by Aniruddh25 — APPROVED** [review]
Looks good overall, left some comments to address.

File: src/Service.Tests/CosmosTests/QueryFilterTests.cs (hunk 2 above)
Comment (abhishekkumams) [reply src/Service.Tests/CosmosTests/QueryFilterTests.cs:424]: it was redundant i added this test as a data row in the tests i added in the current PR

File: src/Service.Tests/SqlTests/GraphQLFilterTests/MsSqlGQLFilterTests.cs (hunk 3 above)
Comment (abhishekkumams) [reply src/Service.Tests/SqlTests/GraphQLFilterTests/MsSqlGQLFilterTests.cs:102]: that is not a character per- se. Its for giving the range. it could be [^a-x] or [^d], there could be so many combinations.

Comment (abhishekkumams) [reply src/Service.Tests/SqlTests/GraphQLFilterTests/MsSqlGQLFilterTests.cs:102]: and just for `^`, escape is not required.

**Review by RubenCerna2079 — APPROVED** [review]
LGTM, I just left a comment

File: src/Service.Tests/SqlTests/RestApiTests/Find/DwSqlFindApiTests.cs [hunk 4]
```diff
@@ -328,7 +328,7 @@ public class DwSqlFindApiTests : FindApiTestBase
             {
                 "FindTestWithFirstSingleKeyPaginationAndOrderBy",
                 $"SELECT TOP 1 * FROM { _integrationTableName } " +
-                $"ORDER BY title asc, id asc " +
+                $"ORDER BY id asc, title asc " +
```
[the remark this answers is not in the document]
Comment (abhishekkumams) [reply src/Service.Tests/SqlTests/RestApiTests/Find/DwSqlFindApiTests.cs:331]: yeah, since we added few more rows, the result was changed as title was used as primary sort key, which doesn't give consistent result, updating it to have id as primary sort key, This test is now consistent and independent of new additions.
