### PR TITLE
Improve mapped column handling for REST pagination and NextLink creation fixes

### LINKED ISSUE #1315: [Bug]: Error "The given key was not present in the dictionary." returned when using mapping and pagination
### What happened?

When mapping is defined and the engine needs to create the cursor token to allow pagination, it generates the "The given key was not present in the dictionary."

Here's configuration file:

```json
{
  "$schema": "https://dataapibuilder.azureedge.net/schemas/v0.5.0-beta/dab.draft.schema.json",
  "data-source": {
    "database-type": "mssql",
    "options": {
      "set-session-context": true
    },
    "connection-string": "Server=localhost; Database=DAB_Todo;User ID=dab_test_user;Password=<redacted>;TrustServerCertificate=true"
  },
  "runtime": {
    "rest": {
      "enabled": true,
      "path": "/api"
    },
    "graphql": {
      "allow-introspection": true,
      "enabled": true,
      "path": "/graphql"
    },
    "host": {
      "mode": "development",
      "cors": {
        "origins": [],
        "allow-credentials": false
      },
      "authentication": {
        "provider": "StaticWebApps"
      }
    }
  },
  "entities": {
    "Todo": {
      "source": {
        "object": "dbo.todos",
        "type": "table"
      },
      "permissions": [
        {
          "role": "anonymous",
          "actions": [
            {
              "action": "read",
              "policy": {
                "database": "@item.visibility eq \u0027public\u0027"
              }
            }
          ]
        },
        {
          "role": "authenticated",
          "actions": [
            {
              "action": "*",
              "policy": {
                "database": "@item.visibility eq @claims.userId"
              }
            }
          ]
        },
        {
          "role": "role1",
          "actions": [
            {
              "action": "*",
              "policy": {
                "database": "@item.visibility eq @claims.userDetails"
              }
            }
          ]
        }
      ],
      "mappings": {
        "owner_id": "visibility",
        "completed": "isDone",
        "id": "tid"
      },
      "rest": {
        "path": "todo"
      }
    }
  }
}
```

and here's the SQL code:

```sql
CREATE TABLE [dbo].[todos]
(
	[id] [uniqueidentifier] NOT NULL,
	[title] [nvarchar](1000) NOT NULL,
	[completed] [bit] NOT NULL,
	[owner_id] [varchar](128) NOT NULL
) 
GO
ALTER TABLE [dbo].[todos] ADD PRIMARY KEY NONCLUSTERED 
(
	[id] ASC
)
GO
ALTER TABLE [dbo].[todos] ADD  DEFAULT (newid()) FOR [id]
GO
ALTER TABLE [dbo].[todos] ADD  DEFAULT ((0)) FOR [completed]
GO
ALTER TABLE [dbo].[todos] ADD  DEFAULT ('public') FOR [owner_id]
GO
DELETE FROM  [dbo].[todos] 
GO
insert into 
    dbo.todos
select 
    newid(),
    'Test Item #' + format([value], '00000'),
    0,
    'public',
    null 
from 
    generate_series(1, 10000, 1)
```

### Version

0.5.34

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

REST

### Relevant log output

```Text
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Find", controller = "Rest"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Find(System.String) on controller Azure.DataApiBuilder.Service.Controllers.RestController (Azure.DataApiBuilder.Service).
dbug: Azure.DataApiBuilder.Service.Resolvers.IQueryExecutor[0]
      6b8d1b92-90c7-41f4-9ada-dfb90b655007: Executing query:
SELECT TOP 101 [dbo_todos].[id] AS [tid], [dbo_todos].[title] AS [title], [dbo_todos].[completed] AS [isDone], [dbo_todos].[owner_id] AS [visibility], [dbo_todos].[position] AS [position] FROM [dbo].[todos] AS [dbo_todos] WHERE ([owner_id] = @param0) ORDER BY [dbo_todos].[id] ASC FOR JSON PATH, INCLUDE_NULL_VALUES
fail: Azure.DataApiBuilder.Service.Controllers.RestController[0]
      6b8d1b92-90c7-41f4-9ada-dfb90b655007: The given key was not present in the dictionary.
fail: Azure.DataApiBuilder.Service.Controllers.RestController[0]
      6b8d1b92-90c7-41f4-9ada-dfb90b655007:    at System.Text.Json.JsonElement.GetProperty(String propertyName)
         at Azure.DataApiBuilder.Service.Resolvers.SqlPaginationUtil.MakeCursorFromJsonElement(JsonElement element, List`1 primaryKey, List`1 orderByColumns, String entityName, String schemaName, String tableName, ISqlMetadataProvider sqlMetadataProvider)
         at Azure.DataApiBuilder.Service.Resolvers.SqlQueryEngine.FormatFindResult(JsonDocument jsonDoc, FindRequestContext context)
         at Azure.DataApiBuilder.Service.Resolvers.SqlQueryEngine.ExecuteAsync(FindRequestContext context)
         at Azure.DataApiBuilder.Service.Services.RestService.ExecuteAsync(String entityName, Operation operationType, String primaryKeyRoute)
         at Azure.DataApiBuilder.Service.Controllers.RestController.HandleOperation(String route, Operation operationType)
info: Microsoft.AspNetCore.Mvc.Infrastructure.SystemTextJsonResultExecutor[1]
      Executing JsonResult, writing value of type '<>f__AnonymousType0`1[[<>f__AnonymousType1`3[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Azure.DataApiBuilder.Service, Version=0.5.34.0, Culture=neutral, PublicKeyToken=null]]'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by seantleonard**
## Why make this change?

- Closes #1315 which highlights an issue with pagination logic not resolving column names from database results using "mapped" column names, when configured. Instead, the current column resolution always uses "backing" column names.

## What is this change?
- changes `TryResolveJsonElementToScalarVariable(element.GetProperty(column)`
  - to: `TryResolveJsonElementToScalarVariable(element.GetProperty(exposedColumnName)`

### Issue when loading request "FindMany" within pagination token 
With a request like ` GET https://localhost:5001/api/todo`
This result is returned as next link: 
```json
"nextLink": "https://localhost:5001/api/todo?System.Collections.Specialized.NameValueCollection"
```
- Fixing the column resolution uncovered this bug with how **initial** pagination next links are generated. (not a problem when a pagination link is included with request). The `NameValueCollection` which contains all query string key/value pairs was not being resolved into a query string and the nextLink looked like:
`"nextLink": "https://localhost:5001/api/todo/System.Collections.Specialized.NameValueCollection"`
  - The fix was to add explicit iteration of the key value pairs in the collection and generate a well-formed Query String using AspNetCore helper utilities.
  - This uncovered a subtle difference in how the engine and test fixture escape query string payload for URLs. Tests were using a helper which incorrectly escaped invalid URI characters with lower case hex value. i.e. `%3d`. Then proper form would be uppercase -> `%3D`
    - Discussion https://stackoverflow.com/a/48301702/18174950
    - https://stackoverflow.com/a/47877559/18174950
    - https://edi.wang/post/2018/11/25/netcore-webutility-urlencode-httputility-urlencode
    - https://stackoverflow.com/a/51829522/18174950

## How was this tested?

- [x] Integration Tests- updated existing integration tests. 
- [ ] Unit Tests

## Sample Request(s)

- Using the configuration/SQL db script provided in the issue, the following request will succeed now and provide a valid NextLink: `https://localhost:5001/api/todo?$orderby=title desc, tid asc`

### CODE REVIEW

File: src/Service/Resolvers/SqlPaginationUtil.cs [hunk 1]
```diff
@@ -494,13 +495,15 @@ public static JsonElement CreateNextLink(string path, NameValueCollection? nvc,
...
+            string queryString = FormatQueryString(queryParameters: nvc);
+
             // ValueKind will be array so we can differentiate from other objects in the response
             // to be returned.
             string jsonString = JsonSerializer.Serialize(new[]
             {
                 new
                 {
-                    nextLink = @$"{path}?{nvc}"
+                    nextLink = @$"{path}{queryString}"
```
[the remark this answers is not in the document]
Comment (seantleonard) [reply src/Service/Resolvers/SqlPaginationUtil.cs:506]: only when the URL lacked query parameters for FindMany. Added test

File: src/Service/Resolvers/SqlPaginationUtil.cs [hunk 2]
```diff
@@ -183,7 +184,7 @@ public static JsonDocument CreatePaginationConnectionFromJsonDocument(JsonDocume
                 if (remainingKeys.Contains(column))
                 {
                     string? exposedColumnName = GetExposedColumnName(entityName, column, sqlMetadataProvider);
-                    if (TryResolveJsonElementToScalarVariable(element.GetProperty(column), out object? value))
+                    if (TryResolveJsonElementToScalarVariable(element.GetProperty(exposedColumnName), out object? value))
```
[the remark this answers is not in the document]
Comment (seantleonard) [reply src/Service/Resolvers/SqlPaginationUtil.cs:185]: The test I just added covers when `orderBy` is not present as a query parameter. (this covers the case you mention). 
Which will then hit the code block which iterates through primary key columns that are used for pagination cursor's `orderBy` query parameter, which is used to break ties between result set records.

File: config-generators/dab-config.sql.reference.json [hunk 3]
```diff
@@ -946,6 +946,39 @@
...
+      ],
+      "rest": true,
+      "graphql": true
+    },
+    "MappedBookmarks": {
+      "source": "mappedbookmarks",
+      "permissions": [
+        {
+          "role": "anonymous",
+          "actions": [ "*" ]
```
Comment (Aniruddh25) [inline config-generators/dab-config.sql.reference.json:974]: shouldn't there be an `authenticated` role added for `mappedbookmarks` too?

File: config-generators/postgresql-commands.txt [hunk 4]
```diff
@@ -104,3 +106,5 @@ update Journal --config "dab-config.PostgreSql.json" --permissions "policy_teste
 update Journal --config "dab-config.PostgreSql.json" --permissions "authorizationHandlerTester:read"
 update ArtOfWar --config "dab-config.PostgreSql.json" --permissions "authenticated:*" --map "DetailAssessmentAndPlanning:始計,WagingWar:作戰,StrategicAttack:謀攻,NoteNum:┬─┬ノ( º _ ºノ)"
 update Sales --config "dab-config.PostgreSql.json" --permissions "authenticated:*"
+update Bookmarks --config "dab-config.PostgreSql.json" --permissions "authenticated:*"
+update MappedBookmarks --config "dab-config.PostgreSql.json" --permissions "authenticated:*" --map "id:bkid,bkname:name"
```
Comment (Aniruddh25) [inline config-generators/postgresql-commands.txt:110]: With the addition of the CONTRIBUTING.md PR, it seems the checked in configs would be used for testing in the pipeline. So, I think you would need to modify the checked in configs. 

The purpose of config generator scripts has now become config validation script now...

File: config-generators/dab-config.sql.reference.json [hunk 5]
```diff
@@ -946,6 +946,39 @@
           "actions": [ "*" ]
         }
       ]
+    },
+    "Bookmarks": {
```
Comment (Aniruddh25) [inline config-generators/dab-config.sql.reference.json:950]: Given the checked in config files in the Test project, we may remove these reference files altogether

File: src/Service.Tests/SqlTests/RestApiTests/Find/FindApiTestBase.cs [hunk 6]
```diff
@@ -447,6 +447,26 @@ public async Task FindTestWithFirstSingleKeyPagination()
             );
         }
 
+        /// <summary>
+        /// Validates that a proper nextLink is created for FindMany requests which do not
+        /// restrict results with query parameters. Engine default paging mechanisms are used
+        /// when > 100 records will be present in result set.
+        /// expectedAfterQueryString starts with ?$, and not &$, because it is the only query parameter.
```
Comment (Aniruddh25) [inline src/Service.Tests/SqlTests/RestApiTests/Find/FindApiTestBase.cs:454]: If it were not the only query parameter does it start with `&$` and is there a test already for that case?

File: config-generators/postgresql-commands.txt (hunk 4 above)
Comment (seantleonard) [reply config-generators/postgresql-commands.txt:110]: Would you prefer I exclude the generator script changes from this PR?

File: config-generators/dab-config.sql.reference.json (hunk 5 above)
Comment (seantleonard) [reply config-generators/dab-config.sql.reference.json:950]: ah gotcha.

File: config-generators/postgresql-commands.txt (hunk 4 above)
Comment (seantleonard) [reply config-generators/postgresql-commands.txt:110]: ah just saw "Given the checked in config files in the Test project, we may remove these reference files altogether"

File: src/Service/Resolvers/SqlPaginationUtil.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (Aniruddh25) [reply src/Service/Resolvers/SqlPaginationUtil.cs:185]: If the test you added for > 100 rows covers the case I mentioned, do we still need the other test for: 
`$select=typeid,int_types`? Does it provide any other coverage Im missing? 

My main motivation to suggest that test was to hit the code block where we missed using the mapped column. If there's no other coverage, we can skip addition of `$select=typeid,int_types` test

**Review by Aniruddh25 — APPROVED** [review]

File: src/Service.Tests/SqlTests/RestApiTests/Find/FindApiTestBase.cs (hunk 6 above)
Comment (seantleonard) [reply src/Service.Tests/SqlTests/RestApiTests/Find/FindApiTestBase.cs:454]: added test coverage for this to Add coverage test for scenario when orderby is one of many query params and is also not the first. Which checks for alternative prefix to after query param: &$ and not ?$

File: config-generators/postgresql-commands.txt (hunk 4 above)
Comment (seantleonard) [reply config-generators/postgresql-commands.txt:110]: since this PR does not have removing config files in scope, will save for separate PR. So will update existing config files until removed.

File: config-generators/dab-config.sql.reference.json (hunk 5 above)
Comment (seantleonard) [reply config-generators/dab-config.sql.reference.json:950]: since this PR does not have removing config files in scope, will save for separate PR. So will update existing config files until removed.

**Review by Aniruddh25 — APPROVED** [review]
LGTM, after simplifying the config files!

File: src/Service/Resolvers/SqlPaginationUtil.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (seantleonard) [reply src/Service/Resolvers/SqlPaginationUtil.cs:185]: yes you're right, ;no need for the `$select=typeid,int_types` which i probably added prior to the >100 row tables, and hadnt finished add the mysql/pgsql queries for that particular test. The >100 row tests cover the code path in question.

File: config-generators/dab-config.sql.reference.json (hunk 5 above)
Comment (seantleonard) [reply config-generators/dab-config.sql.reference.json]: i ended up removing the three reference configs.

**Review by Aniruddh25 — APPROVED** [review]
