### PR TITLE
Fixes the bug #1680 that necessitated adding the 'name' parameter to the @model directive, regardless of the name of the GraphQL object type's name.

### LINKED ISSUE #1680: [Bug]: swa local run returns always "The argument name is invalid. (Parameter 'argumentName')
### What happened?

After I move my azure cloud project to an other subscription group I get this error. BU this error comes only on my local machine Not when I deploy and run my swa an azure.

I get this error:

```{
  "errors": [
    {
      "message": "The argument name is invalid. (Parameter 'argumentName')",
      "locations": [
        {
          "line": 5,
          "column": 3
        }
      ],
      "path": [
        "machine_by_pk"
      ]
    }
  ],
  "data": {
    "machine_by_pk": null
  }
}
```

When I run this query:

```
{
  machine_by_pk(id: "5d4b8c6c-9df0-45fd-9312-40a527c417e5", _partitionKeyValue: "5d4b8c6c-9df0-45fd-9312-40a527c417e5") {
    id
  
  }
}
```

What I not understand is when I run this command local all works fine:

```
{
  machines {
    items {
      id
      type
      companyID
      name
      modelNumber
      location
    }
    endCursor
    hasNextPage
  }
}
```

And I get the machine from the first query, with all values:

```
{
  "data": {
    "machines": {
      "items": [
        {
          "id": "5d4b8c6c-9df0-45fd-9312-40a527c417e5",
          "type": "machine",
          "companyID": "1",
          "name": "maschine 1",
          "modelNumber": null,
          "location": "noLocation"
        },
        {
          "id": "7445e939-4508-40ad-880d-29af612cf93d",
          "type": "machine",
          "companyID": "1",
          "name": "Maschine 2",
          "modelNumber": null,
          "location": "noLocation"
        },
        {
          "id": "9f7c4c21-9945-4ec9-99f7-c7393b5492eb",
          "type": "machine",
          "companyID": "1",
          "name": "machine 3",
          "modelNumber": null,
          "location": "noLocation"
        }
      ],
      "endCursor": null,
      "hasNextPage": false
    }
  }
}
```

I change nothing on my local side without this:

staticwebapp.database.config.json
```
"rest": {
            "enabled": false,
            "path": "/api"
        },
```

Without the local stock will not anymore start.

### Version

swa cli 1.1.4

### What database are you using?

CosmosDB NoSQL

### What hosting model are you using?

_No response_

### Which API approach are you accessing DAB through?

_No response_

### Relevant log output

```Text
"errors": [
    {
      "message": "The argument name is invalid. (Parameter 'argumentName')",
      "locations": [
        {
          "line": 5,
          "column": 3
        }
      ],
      "path": [
        "machine_by_pk"
      ]
    }
  ],
  "data": {
    "machine_by_pk": null
  }
}
```

here the console log for my request.
```
[swa] POST http://localhost:5000/graphql/ (proxy)
[dataApi] info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
[dataApi]       Request starting HTTP/1.1 POST http://localhost:4280/graphql/ application/json 371
[dataApi] info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
[dataApi]       CORS policy execution successful.
[dataApi] info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
[dataApi]       Executing endpoint 'Hot Chocolate GraphQL Pipeline'
[dataApi] fail: Azure.DataApiBuilder.Service.Startup[0]
[dataApi]       The argument name is invalid. (Parameter 'argumentName')
[dataApi] fail: Azure.DataApiBuilder.Service.Startup[0]
[dataApi]          at HotChocolate.Types.Directive.GetArgument[T](String argumentName)
[dataApi]          at Azure.DataApiBuilder.Service.GraphQLBuilder.GraphQLUtils.TryExtractGraphQLFieldModelName(IDirectiveCollection fieldDirectives, String& modelName) in /_/src/Service.GraphQLBuilder/GraphQLUtils.cs:line 181
[dataApi]          at Azure.DataApiBuilder.Core.Resolvers.CosmosQueryStructure.Init(IDictionary`2 queryParams) in /_/src/Core/Resolvers/CosmosQueryStructure.cs:line 113
[dataApi]          at Azure.DataApiBuilder.Core.Resolvers.CosmosQueryEngine.ExecuteAsync(IMiddlewareContext context, IDictionary`2 parameters) in /_/src/Core/Resolvers/CosmosQueryEngine.cs:line 59
[dataApi]          at Azure.DataApiBuilder.Core.Services.ResolverMiddleware.InvokeAsync(IMiddlewareContext context) in /_/src/Core/Services/ResolverMiddleware.cs:line 91
[dataApi]          at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
         at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
[dataApi]          at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
[dataApi] info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
[dataApi]       Executed endpoint 'Hot Chocolate GraphQL Pipeline'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by neeraj-sharma2592**
## Why make this change?
- Closes #1680 
- Regression introduced in 0.8.49 caused required explicitly adding "name" directive for all the model/entity irrespective of whether we are using a different name than the one it originally has. 
- Regression introduced in #1402 when we started using TryExtractGraphQLName as follows:
```
   string typeName = GraphQLUtils.TryExtractGraphQLFieldModelName(underlyingType.Directives, out string? modelName) ?
                    modelName :
                    underlyingType.Name;
```
      
## What is this change?
    Checking Directive "name" exists before accessing its value. 

## How was this tested?
     Tested locally for now. Will be checking Test cases for it.
- [x] Integration Tests
- [ ] Unit Tests

### CODE REVIEW

**Review by seantleonard — COMMENTED** [review]
Thanks for addressing and looks good so far. Looking forward to seeing a test before merging.

File: src/Service.GraphQLBuilder/GraphQLUtils.cs [hunk 1]
```diff
@@ -182,10 +182,13 @@ public static bool TryExtractGraphQLFieldModelName(IDirectiveCollection fieldDir
             {
                 if (dir.Name.Value == ModelDirectiveType.DirectiveName)
                 {
-                    dir.ToObject<ModelDirectiveType>();
-                    modelName = dir.GetArgument<string>(ModelDirectiveType.ModelNameArgument).ToString();
+                    ModelDirectiveType modelDirectiveType = dir.ToObject<ModelDirectiveType>();
 
-                    return modelName is not null;
+                    if(modelDirectiveType.Name.HasValue)
```
Comment (Aniruddh25) [inline src/Service.GraphQLBuilder/GraphQLUtils.cs:187]: Could you please point to which change specifically caused this regression in 0.8 for better understanding? We have release branches here: `release/0.8`, `release/0.7`

File: src/Service.GraphQLBuilder/GraphQLUtils.cs [hunk 2]
```diff
@@ -182,10 +182,13 @@ public static bool TryExtractGraphQLFieldModelName(IDirectiveCollection fieldDir
             {
                 if (dir.Name.Value == ModelDirectiveType.DirectiveName)
                 {
-                    dir.ToObject<ModelDirectiveType>();
-                    modelName = dir.GetArgument<string>(ModelDirectiveType.ModelNameArgument).ToString();
+                    ModelDirectiveType modelDirectiveType = dir.ToObject<ModelDirectiveType>();
```
Comment (Aniruddh25) [inline src/Service.GraphQLBuilder/GraphQLUtils.cs:185]: nit: from the PR description, please remove your branch name and make it more readable - the same description goes into release notes so it should be understandable to our developer consumers.

**Comment by neeraj-sharma2592** [comment]
> Thanks for addressing and looks good so far. Looking forward to seeing a test before merging.

I have modified the schema to test this scenario. We had a 'name' attribute for each model, and we couldn't identify this regression through our integration tests. Please let me know if this seems correct.

https://github.com/Azure/data-api-builder/blob/99f1910afeec044813d69d8badfd901e99441e68/src/Service.Tests/CosmosTests/TestBase.cs#L44

File: src/Service.GraphQLBuilder/GraphQLUtils.cs (hunk 1 above)
Comment (neeraj-sharma2592) [reply src/Service.GraphQLBuilder/GraphQLUtils.cs]: We introduced this change in release/0.8
https://github.com/Azure/data-api-builder/blob/99f1910afeec044813d69d8badfd901e99441e68/src/Core/Resolvers/CosmosQueryStructure.cs#L120 

In earlier release we were not using this 
https://github.com/Azure/data-api-builder/blob/61de247acf65280d93783072226f695536591ffb/src/Service/Resolvers/CosmosQueryStructure.cs#L123C1-L124C1

Comment (Aniruddh25) [reply src/Service.GraphQLBuilder/GraphQLUtils.cs]: Thank you @neeraj-sharma2592 for identifying this!

**Review by Aniruddh25 — APPROVED** [review]

**Review by Aniruddh25 — APPROVED** [review]
LGTM, thanks alot for the quick fix and the test!!

**Review by seantleonard — APPROVED** [review]
Thanks for adding a test and pushing this fix.
