### PR TITLE
Fix dab validate error messaging when logger is not available

### LINKED ISSUE #3268: [Bug]: Schema validation fail in `dab config` throws exception
## What?

When running `dab validate` and there is neither `autoentities` nor `entities` (or any other reason the JSON Schema validation would fail) it should report this as a validation error, not throw an exception. 

### Current output

```
C:\Temp\dab-todo-test>dab validate
Information: Microsoft.DataApiBuilder 2.0.0
Information: Config not provided. Trying to get default config based on DAB_ENVIRONMENT...
Information: Environment variable DAB_ENVIRONMENT is Development
Information: Validating config file: dab-config.json
Deserialization of the configuration file failed during a post-processing step.
Message:
 Configuration file should contain either at least the entities or autoentities property
Stack Trace:
    at Azure.DataApiBuilder.Config.ObjectModel.RuntimeConfig..ctor(String Schema, DataSource DataSource, RuntimeEntities Entities, RuntimeAutoentities Autoentities, RuntimeOptions Runtime, DataSourceFiles DataSourceFiles, AzureKeyVaultOptions AzureKeyVault) in /_/src/Config/ObjectModel/RuntimeConfig.cs:line 317
   at .ctor(Object[])
   at System.Text.Json.Serialization.Converters.LargeObjectWithParameterizedConstructorConverter`1.CreateObject(ReadStackFrame& frame)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Azure.DataApiBuilder.Config.RuntimeConfigLoader.TryParseConfig(String json, RuntimeConfig& config, DeserializationVariableReplacementSettings replacementSettings, ILogger logger, String connectionString) in /_/src/Config/RuntimeConfigLoader.cs:line 215    
Information: Failed to parse the config file
Error: Config is invalid. Check above logs for details.
```

### Desired output

```
C:\Temp\dab-todo-test>dab validate
Information: Microsoft.DataApiBuilder 2.0.0
Information: Validating config file: dab-config.json
Error: Configuration file should contain either at least the entities or autoentities property
Information: Config is invalid. 
```

Image

### PR DESCRIPTION
**Pull request by aaronburtle**
## Why make this change?

Closes https://github.com/Azure/data-api-builder/issues/3268

## What is this change?

When `dab validate` or `dab start` encounters a config parsing error (e.g. missing entities/autoentities), the CLI previously dumped the full exception message and stack trace to stderr. This made the output noisy and unhelpful. After this change, only a clean, descriptive validation message is shown.

The key design changes:

- `TryParseConfig` is now a pure function that returns an `out string? parseError` message on failure instead of writing to `Console.Error` or `ILogger` internally. Error reporting is the caller's responsibility.
- `FileSystemRuntimeConfigLoader.TryLoadConfig` writes the `parseError` to `Console.Error` (because config is parsed before the DI container and logger are available, so the log buffer would never be flushed on a parse failure) and sets an instance-scoped `IsParseErrorEmitted` flag so CLI callers (`ConfigGenerator`) can avoid logging duplicate messages.
- `ConfigGenerator.IsConfigValid` now has an explicit early-return path when config parsing fails (via `runtimeConfigProvider.TryGetConfig`), using `IsParseErrorEmitted` to suppress duplicate output.
- `ValidateOptions.Handler` uses `LogError("Config is invalid.")`.
- Comments referencing which method emits the error to `Console.Error` corrected to `TryLoadConfig` (not `TryParseConfig`).

## How was this tested?

* `ValidateConfigTests.cs` — Added `TestValidateConfigWithNoEntitiesProducesCleanError` (new test verifying clean error message, no stack traces).
* `EnvironmentTests.cs` — Updated `FailureToStartEngineWhenEnvVarNamedWrong` to match the new single-line clean stderr format.
* `EndToEndTests.cs` — Simplified assertions in `TestExitOfRuntimeEngineWithInvalidConfig` (this test is Ignored but updated for consistency).
* `RuntimeConfigLoaderTests.cs` — Updated `FailLoadMultiDataSourceConfigDuplicateEntities` to assert `loader.IsParseErrorEmitted` is true.

### CODE REVIEW

File: src/Cli/ConfigGenerator.cs [hunk 1]
```diff
@@ -2564,7 +2564,9 @@ public static bool TryStartEngineWithOptions(StartOptions options, FileSystemRun
             // Replaces all the environment variables while deserializing when starting DAB.
             if (!loader.TryLoadKnownConfig(out RuntimeConfig? deserializedRuntimeConfig, replaceEnvVar: true))
             {
-                _logger.LogError("Failed to parse the config file: {runtimeConfigFile}.", runtimeConfigFile);
+                string? parseError = RuntimeConfigLoader.LastParseError;
+                RuntimeConfigLoader.LastParseError = null;
+                _logger.LogError("{parseError}", parseError ?? $"Failed to parse the config file: {runtimeConfigFile}.");
```
[the remark this answers is not in the document]
Comment (aaronburtle) [reply src/Cli/ConfigGenerator.cs]: This is valid but the better approach is to route everything through the CLI logger.

File: src/Cli/ConfigGenerator.cs [hunk 2]
```diff
@@ -2643,6 +2645,28 @@ public static bool IsConfigValid(ValidateOptions options, FileSystemRuntimeConfi
...
+            Console.SetError(TextWriter.Null);
+            bool configLoaded;
+            try
+            {
+                configLoaded = runtimeConfigProvider.TryGetConfig(out RuntimeConfig? _);
+            }
+            finally
+            {
+                Console.SetError(originalError);
+            }
```
[the remark this answers is not in the document]
Comment (aaronburtle) [reply src/Cli/ConfigGenerator.cs]: this has been reverted, we now use console when there is no logger available.

File: src/Config/RuntimeConfigLoader.cs [hunk 3]
```diff
@@ -38,6 +38,12 @@ public abstract class RuntimeConfigLoader
 
     public bool IsNewConfigValidated;
 
+    /// <summary>
+    /// Stores the last config parse error message for callers that need
+    /// to retrieve and log it through their own logging infrastructure.
+    /// </summary>
+    public static string? LastParseError { get; set; }
+
```
[the remark this answers is not in the document]
Comment (aaronburtle) [reply src/Config/RuntimeConfigLoader.cs]: valid, refactoring.

File: src/Config/RuntimeConfigLoader.cs [hunk 4]
```diff
@@ -263,17 +269,19 @@ public static bool TryParseConfig(string json,
             ex is JsonException ||
             ex is DataApiBuilderException)
         {
-            string errorMessage = ex is JsonException ? "Deserialization of the configuration file failed." :
-                "Deserialization of the configuration file failed during a post-processing step.";
+            // Store the parse error so callers (e.g. CLI) can retrieve and
+            // log it through their own structured logging infrastructure.
+            LastParseError = ex is DataApiBuilderException
+                ? ex.Message
+                : $"Deserialization of the configuration file failed. {ex.Message}";
```
[the remark this answers is not in the document]
Comment (aaronburtle) [reply src/Config/RuntimeConfigLoader.cs]: refactor covers this case.

**Comment by aaronburtle** [comment]
@copilot can you do another PR review please.

File: src/Cli/Commands/ValidateOptions.cs [hunk 5]
```diff
@@ -38,7 +38,7 @@ public int Handler(ILogger logger, FileSystemRuntimeConfigLoader loader, IFileSy
             }
             else
             {
-                logger.LogError("Config is invalid. Check above logs for details.");
+                logger.LogError("Config is invalid.");
```
Comment (souvikghosh04) [inline src/Cli/Commands/ValidateOptions.cs:41]: is this always dependant on the `IsParseErrorEmitted` or will there be any scenario where config is invalid and there is no logs above?

File: src/Cli.Tests/EndToEndTests.cs [hunk 6]
```diff
@@ -1093,11 +1093,6 @@ public async Task TestExitOfRuntimeEngineWithInvalidConfig(
...
             output = await process.StandardError.ReadLineAsync();
             Assert.IsNotNull(output);
-            StringAssert.Contains(output, $"Deserialization of the configuration file failed.", StringComparison.Ordinal);
-
-            output = await process.StandardOutput.ReadLineAsync();
-            Assert.IsNotNull(output);
-            StringAssert.Contains(output, $"Error: Failed to parse the config file: {TEST_RUNTIME_CONFIG_FILE}.", StringComparison.Ordinal);
 
             output = await process.StandardOutput.ReadLineAsync();
             Assert.IsNotNull(output);
```
Comment (souvikghosh04) [inline src/Cli.Tests/EndToEndTests.cs:1099]: this seems duplicated. also, previously there were additional assertions.

File: src/Core/Configurations/RuntimeConfigProvider.cs [hunk 7]
```diff
@@ -269,7 +270,7 @@ public async Task<bool> Initialize(
 
         IsLateConfigured = true;
 
-        if (RuntimeConfigLoader.TryParseConfig(jsonConfig, out RuntimeConfig? runtimeConfig, replacementSettings))
+        if (RuntimeConfigLoader.TryParseConfig(jsonConfig, out RuntimeConfig? runtimeConfig, out string? _, replacementSettings))
```
Comment (souvikghosh04) [inline src/Core/Configurations/RuntimeConfigProvider.cs]: nit: can we just do `out _` instead of `out string? _`?

**Review by souvikghosh04 — COMMENTED** [review]
posting comments so far

File: src/Cli/Commands/ValidateOptions.cs (hunk 5 above)
Comment (aaronburtle) [reply src/Cli/Commands/ValidateOptions.cs:41]: We are not always dependent on `IsParseErrorEmitted` here, but also there will not be any scenario where we do not have logs. We use `IsParseErrorEmitted` to prevent duplicate log entries when the loader has already written the deserialization error to Console. This is because we dont yet have a mechanism for flushing the log buffer at this stage in startup, so if we dont go to console, the error will be silently swallowed. There is a PR with a comment to add this, so whenever that comes, either in that PR or a followup, this needs to be changed so we are always going to the log buffer.

File: src/Cli.Tests/EndToEndTests.cs (hunk 6 above)
Comment (aaronburtle) [reply src/Cli.Tests/EndToEndTests.cs:1099]: cleaned this up, some of the assertions are no longer valid, so they will remain out.

File: src/Service.Tests/OpenApiDocumentor/MissingRoleNotFoundTests.cs [hunk 8]
```diff
@@ -1,98 +0,0 @@
-// Copyright (c) Microsoft Corporation.
-// Licensed under the MIT License.
-
-using System;
-using System.Collections.Generic;
-using System.IO;
-using System.IO.Abstractions;
-using System.Net;
-using System.Net.Http;
-using System.Text.Json;
```
Comment (Aniruddh25) [inline src/Service.Tests/OpenApiDocumentor/MissingRoleNotFoundTests.cs:10]: Why is this file/test being deleted?

File: src/Config/FileSystemRuntimeConfigLoader.cs [hunk 9]
```diff
@@ -303,6 +311,13 @@ public bool TryLoadConfig(
                 RuntimeConfig = LastValidRuntimeConfig;
             }
 
+            IsParseErrorEmitted = parseError is not null;
+
+            if (parseError is not null)
+            {
+                Console.Error.WriteLine(parseError);
```
Comment (Aniruddh25) [inline src/Config/FileSystemRuntimeConfigLoader.cs:316]: Instead of directly writing to console here since the logger is not initialized yet, leverage the LogBuffer fix in this PR: https://github.com/Azure/data-api-builder/pull/3318 so that the loglevel is still honored. Depending on if that PR merges first or yours.

Comment (Aniruddh25) [inline src/Config/FileSystemRuntimeConfigLoader.cs:316]: it seems the boolean IsParseErrorEmitted should be set to true after log is written either to the console or to the logbuffer from #3318 inside this if clause. 

Conditioning IsParseErrorEmitted on where parseError is not null is incorrect since the error could be present but not yet emitted.

File: src/Service.Tests/Configuration/RuntimeConfigLoaderTests.cs [hunk 10]
```diff
@@ -93,14 +93,10 @@ public async Task FailLoadMultiDataSourceConfigDuplicateEntities(string configPa
...
-        StringWriter sw = new();
-        Console.SetError(sw);
-
         loader.TryLoadConfig("dab-config.json", out RuntimeConfig _);
-        string error = sw.ToString();
 
-        Assert.IsTrue(error.StartsWith("Deserialization of the configuration file failed during a post-processing step."));
-        Assert.IsTrue(error.Contains("An item with the same key has already been added."));
+        Assert.IsTrue(loader.IsParseErrorEmitted,
+            "IsParseErrorEmitted should be true when config parsing fails.");
```
Comment (Aniruddh25) [inline src/Service.Tests/Configuration/RuntimeConfigLoaderTests.cs:102]: We should also assert that the console log error was actually emitted if the IsParseErrorEmitted flag is really true.

**Review by Aniruddh25 — CHANGES_REQUESTED** [review]
Waiting on merge with #3318

File: src/Service.Tests/OpenApiDocumentor/MissingRoleNotFoundTests.cs (hunk 8 above)
Comment (aaronburtle) [reply src/Service.Tests/OpenApiDocumentor/MissingRoleNotFoundTests.cs:10]: This leaked from another branch during a local merge. Not related to this PR.

File: src/Config/FileSystemRuntimeConfigLoader.cs (hunk 9 above)
Comment (aaronburtle) [reply src/Config/FileSystemRuntimeConfigLoader.cs:316]: We need the logic so that we still flush the log buffer even in the case of an exception, otherwise these errors will get swallowed. But once that is in, if it merges first, will change this logic to utilize, or otherwise can merge this into that PR as you said depending on which merges in first.

Comment (aaronburtle) [reply src/Config/FileSystemRuntimeConfigLoader.cs:316]: i left that comment about still flushing on exception on the other PR too so it doesnt get lost.

Comment (RubenCerna2079) [reply src/Config/FileSystemRuntimeConfigLoader.cs:316]: I think this can be merged first and I can add the LogBuffer to it, just let me know when this PR is merged so I can make the changes. And if there are any other sections that will need changes like this one.

File: src/Service.Tests/OpenApiDocumentor/MissingRoleNotFoundTests.cs (hunk 8 above)
Comment (Aniruddh25) [reply src/Service.Tests/OpenApiDocumentor/MissingRoleNotFoundTests.cs:10]: But you are now actually deleting this from main as well if I approve and merge this PR. Is this what you intend? Is there another PR that will add it back to main?

Comment (aaronburtle) [reply src/Service.Tests/OpenApiDocumentor/MissingRoleNotFoundTests.cs:10]: The other branch merged main, and strangely it still showed as deleting on this branch, I updated so we ignore this file now that its a part of main.

**Review by Aniruddh25 — APPROVED** [review]

**Review by souvikghosh04 — APPROVED** [review]
LGTM. thanks for addressing the comments
