### PR TITLE
Fixing unintended update to GraphQL operation when updating REST methods

### LINKED ISSUE #1554: Updating rest methods leads to an update to grapql operations
I want to bring to attention the following scenario which breaks and can be a bug.

1. Creating a stored procedure entity with graphql configured for Query

Command: `dab add getbooks --source "get_books" --source.type "stored-procedure" --permissions "anonymous:execute" --graphql.operation "query" `
Config Json (just the entities section):

```json
 "entities": {
    "getbooks": {
  "source": {
    "object": "get_books",
    "type": "stored-procedure",
    "parameters": null,
    "key-fields": null
  },
  "graphql": {
    "enabled": true,
    "operation": "query",
    "type": {
      "singular": "getbooks",
      "plural": "getbooks"
    }
  },
  "rest": {
    "enabled": true,
    "path": null,
    "methods": [
      "post"
    ]
  },
  "permissions": [
    {
      "role": "anonymous",
      "actions": [
        {
          "action": "execute",
          "fields": null,
          "policy": {
            "request": null,
            "database": null
          }
        }
      ]
    }
  ],
  "mappings": null,
  "relationships": null
}
  }
```

2. Update the rest method to GET
Command: `dab update getbooks --rest.methods "GET"`

Config Json:
```json
"entities": {
    "getbooks": {
  "source": {
    "object": "get_books",
    "type": "stored-procedure",
    "parameters": null,
    "key-fields": null
  },
  "graphql": {
    "enabled": true,
    "operation": "mutation",
    "type": {
      "singular": "getbooks",
      "plural": "getbooks"
    }
  },
  "rest": {
    "enabled": true,
    "path": null,
    "methods": [
      "get"
    ]
  },
  "permissions": [
    {
      "role": "anonymous",
      "actions": [
        {
          "action": "execute",
          "fields": null,
          "policy": {
            "request": null,
            "database": null
          }
        }
      ]
    }
  ],
  "mappings": null,
  "relationships": null
}
  }

```
When updating the rest.methods, the graphql operation has lost its original value of `query`. It now has the default value of `mutation`.

This scenario works fine in the current main branch.  Please find below the commands and the config jsons generated using the main branch.

1. Creating a new stored procedure entity
 Command: `dab add getbooks --source "getbooks" --source.type "stored-procedure" --permissions "anonymous:execute" --graphql.operation "query"`

Config json:

```json
"entities": {
    "getbooks": {
      "source": {
        "type": "stored-procedure",
        "object": "getbooks"
      },
      "permissions": [
        {
          "role": "anonymous",
          "actions": [
            "execute"
          ]
        }
      ],
      "rest": {
        "methods": [
          "post"
        ]
      },
      "graphql": {
        "operation": "query"
      }
    }
  }
```
2. Updating the rest methods 
Command: `dab update getbooks --rest.methods "get"`
Config json:
```json
"entities": {
    "getbooks": {
      "source": {
        "type": "stored-procedure",
        "object": "getbooks"
      },
      "permissions": [
        {
          "role": "anonymous",
          "actions": [
            "execute"
          ]
        }
      ],
      "rest": {
        "methods": [
          "get"
        ]
      },
      "graphql": {
        "operation": "query"
      }
    }
  }
```
The value present in the graphql operation is preserved. Only the rest methods are updated.

Would greatly appreciate if you could take a look at this.

_Originally posted by @severussundar in https://github.com/Azure/data-api-builder/issues/1402#issuecomment-1607705270_

### PR DESCRIPTION
**Pull request by severussundar**
## Why make this change?

- Closes #1554 
1. Creating a stored procedure entity with graphql configured for Query

Command: `dab add getbooks --source "get_books" --source.type "stored-procedure" --permissions "anonymous:execute" --graphql.operation "query" `
Config Json (just the entities section):

```json
 "entities": {
    "getbooks": {
  "source": {
    "object": "get_books",
    "type": "stored-procedure",
    "parameters": null,
    "key-fields": null
  },
  "graphql": {
    "enabled": true,
    "operation": "query",
    "type": {
      "singular": "getbooks",
      "plural": "getbooks"
    }
  },
  "rest": {
    "enabled": true,
    "path": null,
    "methods": [
      "post"
    ]
  },
  "permissions": [
    {
      "role": "anonymous",
      "actions": [
        {
          "action": "execute",
          "fields": null,
          "policy": {
            "request": null,
            "database": null
          }
        }
      ]
    }
  ],
  "mappings": null,
  "relationships": null
}
  }
```

2. Update the rest method to GET
Command: `dab update getbooks --rest.methods "GET"`

Config Json:
```json
"entities": {
    "getbooks": {
  "source": {
    "object": "get_books",
    "type": "stored-procedure",
    "parameters": null,
    "key-fields": null
  },
  "graphql": {
    "enabled": true,
    "operation": "mutation",
    "type": {
      "singular": "getbooks",
      "plural": "getbooks"
    }
  },
  "rest": {
    "enabled": true,
    "path": null,
    "methods": [
      "get"
    ]
  },
  "permissions": [
    {
      "role": "anonymous",
      "actions": [
        {
          "action": "execute",
          "fields": null,
          "policy": {
            "request": null,
            "database": null
          }
        }
      ]
    }
  ],
  "mappings": null,
  "relationships": null
}
  }

```
When updating the rest.methods, the graphql operation has lost its original value of `query`. It now has the default value of `mutation`.

## What is this change?

-  `ConfigGenerator.ConstructUpdatedGraphQLDetails()`:  When GraphQL operation is not updated, logic for preserving the existing configured graphQL operation is added
- `EndToEndTests.TestUpdatingStoredProcedureWithRestMethods()`: Adds a test case with the mentioned repro steps

## How was this tested?

- [x] Unit Tests
- [x] Manual Tests

## Sample Request(s)

- `dab add getbooks --source "getbooks" --source.type "stored-procedure" --permissions "anonymous:execute" --graphql.operation "query"`

```json
 "entities": {
    "getbooks": {
  "source": {
    "object": "getbooks",
    "type": "stored-procedure",
    "parameters": null,
    "key-fields": null
  },
  "graphql": {
    "enabled": true,
    "operation": "query",
    "type": {
      "singular": "getbooks",
      "plural": "getbooks"
    }
  },
  "rest": {
    "enabled": true,
    "path": null,
    "methods": [
      "post"
    ]
  },
  "permissions": [
    {
      "role": "anonymous",
      "actions": [
        {
          "action": "execute",
          "fields": null,
          "policy": {
            "request": null,
            "database": null
          }
        }
      ]
    }
  ],
  "mappings": null,
  "relationships": null
}
  }
```
- `dab update getbooks --rest.methods "get,patch"`

```json
 "entities": {
    "getbooks": {
  "source": {
    "object": "getbooks",
    "type": "stored-procedure",
    "parameters": null,
    "key-fields": null
  },
  "graphql": {
    "enabled": true,
    "operation": "query",
    "type": {
      "singular": "getbooks",
      "plural": "getbooks"
    }
  },
  "rest": {
    "enabled": true,
    "path": null,
    "methods": [
      "get",
      "patch"
    ]
  },
  "permissions": [
    {
      "role": "anonymous",
      "actions": [
        {
          "action": "execute",
          "fields": null,
          "policy": {
            "request": null,
            "database": null
          }
        }
      ]
    }
  ],
  "mappings": null,
  "relationships": null
}
```
The `rest.methods` field is updated with the right values and the existing value of `graphql.operation` is preserved

### CODE REVIEW

File: src/Cli/ConfigGenerator.cs [hunk 1]
```diff
@@ -1094,7 +1094,7 @@ private static EntityGraphQLOptions ConstructUpdatedGraphQLDetails(Entity entity
         {
             //Updated GraphQL Type
             EntityGraphQLOptions graphQLType = (options.GraphQLType is not null) ? ConstructGraphQLTypeDetails(options.GraphQLType, null) : entity.GraphQL;
-            GraphQLOperation? graphQLOperation = null;
+            GraphQLOperation? graphQLOperation;
```
Comment (aaronpowell) [inline src/Cli/ConfigGenerator.cs:1097]: do we not need to initialise the value anymore?

Comment (severussundar) [reply src/Cli/ConfigGenerator.cs:1097]: No, Visual Studio complains of redundant assignment when initialized with `null`.

**Review by aaronpowell — APPROVED** [review]
Looks good. Waiting for the tests to pass.

I like that we have another Verify test in there!

**Review by abhishekkumams — APPROVED** [review]
