### PR TITLE
Fix autoentity validation & CLI/Schema mismatch bugs

### LINKED ISSUE #3335: [Bug]: autoentities and dab validate
## dab validate throws unhandled exception on autoentity/entity name conflict

@RubenCerna2079, I cannot be sure, maybe you have already resolved this.

### Error
```
Unhandled exception. System.AggregateException: One or more errors occurred.
(Entity with name 'Todo' already exists. Cannot create new entity from autoentity pattern with definition-name 'my-def'.)
```
### Expected
```
Error: Entity 'Todo' conflicts with autoentity pattern 'my-def'. Use --patterns.exclude to skip it.
```
### Repro
```
dab init --database-type mssql --connection-string "..." --config test.json
dab add Todo -s "dbo.Todo" --permissions "anonymous:*" --config test.json
dab auto-config my-def --patterns.include "dbo.%" --permissions "anonymous:read" --config test.json
dab validate --config test.json
```

### LINKED ISSUE #3375: [Bug]: Invalid CLI dab auto-config --template.mcp.dml-tool
Singular vs plural naming mismatch: dml-tool vs dml-tools.
### Cli
template.mcp.dml-tool (singular)
### Schema
autoentities.<name>.template.mcp.dml-tools

### PR DESCRIPTION
**Pull request by RubenCerna2079**
## Why make this change?
- #3375 
  - The CLI and the schema have a mismatch in the `autoentities.<def-name>.template.mcp.dml-tools`, need to ensure that they are the same.
- #3335 
  - Using `dab validate` produces the wrong output message.

## What is this change?
For issue #3375:
- We changed the `AutoConfigOption.cs` file so that it uses the proper name and changed the name of the variable to also match the schema in the `ConfigGenerator.cs`.

For issue #3335:
-  We changed the log message in `MsSqlMetadataProvider.cs` so that it is easier for the user to understand the error.

## How was this tested?

- [ ] Integration Tests
- [ ] Unit Tests
- [x] Local Testing
The issues were related to mismatches or to the output of log messages that can only be tested locally.

## Sample Request(s)
dab auto-config <def-name> --template.mcp.dml-tools true/false
dab validate --config test.json

### CODE REVIEW

File: src/Cli/Commands/AutoConfigOptions.cs [hunk 1]
```diff
@@ -61,8 +61,8 @@ public AutoConfigOptions(
         [Option("patterns.name", Required = false, HelpText = "Interpolation syntax for entity naming (must be unique for each generated entity). Default: '{object}'")]
         public string? PatternsName { get; }
 
-        [Option("template.mcp.dml-tool", Required = false, HelpText = "Enable/disable DML tools for generated entities. Allowed values: true, false. Default: true")]
-        public string? TemplateMcpDmlTool { get; }
+        [Option("template.mcp.dml-tools", Required = false, HelpText = "Enable/disable DML tools for generated entities. Allowed values: true, false. Default: true")]
+        public string? TemplateMcpDmlTools { get; }
```
Comment (souvikghosh04) [inline src/Cli/Commands/AutoConfigOptions.cs:65]: do we have test coverage for this and the below changes?

File: src/Cli/ConfigGenerator.cs [hunk 2]
```diff
@@ -2646,45 +2646,63 @@ public static bool IsConfigValid(ValidateOptions options, FileSystemRuntimeConfi
...
+                // Additional validation: warn if fields are missing and MCP is enabled
+                if (isValid)
                 {
-                    bool mcpEnabled = config.IsMcpEnabled;
-                    if (mcpEnabled)
+                    if (runtimeConfigProvider.TryGetConfig(out RuntimeConfig? config) && config is not null)
                     {
-                        foreach (KeyValuePair<string, Entity> entity in config.Entities)
+                        bool mcpEnabled = config.IsMcpEnabled;
+                        if (mcpEnabled)
```
Comment (souvikghosh04) [inline src/Cli/ConfigGenerator.cs]: nit: just use `config.IsMcpEnabled` instead of a new variable

File: src/Cli/ConfigGenerator.cs [hunk 3]
```diff
@@ -2646,45 +2646,63 @@ public static bool IsConfigValid(ValidateOptions options, FileSystemRuntimeConfi
...
                     }
                 }
+
+                return isValid;
             }
+            catch (AggregateException ex)
+            {
+                foreach (Exception exception in ex.InnerExceptions)
+                {
+                    _logger.LogError(exception, exception.Message);
```
Comment (souvikghosh04) [inline src/Cli/ConfigGenerator.cs]: you might not need to pass the `exception` object. just the message as its done in other places.

File: src/Cli/ConfigGenerator.cs [hunk 4]
```diff
@@ -2646,45 +2646,63 @@ public static bool IsConfigValid(ValidateOptions options, FileSystemRuntimeConfi
...
+                }
 
-            return isValid;
+                return isValid;
+            }
+            catch (Exception ex)
+            {
+                _logger.LogError(ex, ex.Message);
```
Comment (souvikghosh04) [inline src/Cli/ConfigGenerator.cs]: same here

**Review by souvikghosh04 — CHANGES_REQUESTED** [review]
Added some comments

File: src/Cli/ConfigGenerator.cs [hunk 5]
```diff
@@ -2646,45 +2646,63 @@ public static bool IsConfigValid(ValidateOptions options, FileSystemRuntimeConfi
...
+                            }
                         }
                     }
                 }
+
+                return isValid;
             }
+            catch (AggregateException ex)
+            {
+                foreach (Exception exception in ex.InnerExceptions)
```
[the remark this answers is not in the document]
Comment (RubenCerna2079) [reply src/Cli/ConfigGenerator.cs]: Changes were reverted

File: src/Cli/ConfigGenerator.cs [hunk 6]
```diff
@@ -2646,45 +2646,63 @@ public static bool IsConfigValid(ValidateOptions options, FileSystemRuntimeConfi
...
+                }
 
-            return isValid;
+                return isValid;
+            }
+            catch (Exception ex)
+            {
+                _logger.LogError(ex, ex.Message);
+                return isValid;
+            }
```
[the remark this answers is not in the document]
Comment (RubenCerna2079) [reply src/Cli/ConfigGenerator.cs]: Changes were reverted

File: src/Cli/Commands/AutoConfigOptions.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (RubenCerna2079) [reply src/Cli/Commands/AutoConfigOptions.cs:65]: This is a new CLI command so the only people using the old alias are using a release candidate, which is prone to changing

File: src/Core/Services/MetadataProviders/MsSqlMetadataProvider.cs [hunk 7]
```diff
@@ -357,7 +357,7 @@ protected override async Task GenerateAutoentitiesIntoEntities(IReadOnlyDictiona
                     if (!entities.TryAdd(entityName, generatedEntity) || !runtimeConfig.TryAddGeneratedAutoentityNameToDataSourceName(entityName, autoentityName))
                     {
                         throw new DataApiBuilderException(
-                            message: $"Entity with name '{entityName}' already exists. Cannot create new entity from autoentities definition '{autoentityName}'.",
+                            message: $"Entity '{entityName}' conflicts with autoentity pattern '{autoentityName}'. Use --patterns.exclude to skip it.",
```
[the remark this answers is not in the document]
Comment (RubenCerna2079) [reply src/Core/Services/MetadataProviders/MsSqlMetadataProvider.cs:360]: The message was already decided beforehand by @JerryNixon.

File: src/Cli/ConfigGenerator.cs (hunk 2 above)
Comment (RubenCerna2079) [reply src/Cli/ConfigGenerator.cs]: I deleted this section since I saw that @aaronburtle was already solving this issue in his PR https://github.com/Azure/data-api-builder/pull/3311

File: src/Cli/ConfigGenerator.cs (hunk 3 above)
Comment (RubenCerna2079) [reply src/Cli/ConfigGenerator.cs]: I deleted this section since I saw that @aaronburtle was already solving this issue in his PR https://github.com/Azure/data-api-builder/pull/3311

File: src/Cli/ConfigGenerator.cs (hunk 4 above)
Comment (RubenCerna2079) [reply src/Cli/ConfigGenerator.cs]: I deleted this section since I saw that @aaronburtle was already solving this issue in his PR https://github.com/Azure/data-api-builder/pull/3311

File: src/Cli/Commands/AutoConfigOptions.cs (hunk 1 above)
Comment (RubenCerna2079) [reply src/Cli/Commands/AutoConfigOptions.cs:65]: This cannot really be tested since it was a mismatch between the CLI and the schema, if you mean if we even test this flag there are tests that already do it.
As for the other changes I got rid of them since the PR https://github.com/Azure/data-api-builder/pull/3311 already takes care of those issues.

File: src/Cli/ConfigGenerator.cs [hunk 8]
```diff
@@ -3109,11 +3109,11 @@ private static AutoentityPatterns BuildAutoentityPatterns(AutoConfigOptions opti
             bool userProvidedCache = existingAutoentity?.Template.UserProvidedCacheOptions ?? false;
 
             // Update MCP options
-            if (!string.IsNullOrWhiteSpace(options.TemplateMcpDmlTool))
+            if (!string.IsNullOrWhiteSpace(options.TemplateMcpDmlTools))
```
Comment (Aniruddh25) [inline src/Cli/ConfigGenerator.cs:3112]: The PR description says:

"We also added a try-catch to the validation logic in the ConfigGenerator.cs so that instead of outputing an exception when dab throws an error it just logs the exception."

Where is this try-catch?

**Review by Aniruddh25 — CHANGES_REQUESTED** [review]
Not certain if the changes really work for issue #3335

File: src/Cli/ConfigGenerator.cs (hunk 8 above)
Comment (souvikghosh04) [reply src/Cli/ConfigGenerator.cs:3112]: @RubenCerna2079 recent commit reverted the validation? is this accurate or the description should be updated?
image

**Review by souvikghosh04 — APPROVED** [review]
Approving it based on the comments addressed. PR description might need to be updated based on the recent changes made.

File: src/Cli/ConfigGenerator.cs (hunk 8 above)
Comment (RubenCerna2079) [reply src/Cli/ConfigGenerator.cs:3112]: Reverted that change since it was already fixed by Aaron in one of his PRs. Also, just removed it from the PR description.

**Review by Aniruddh25 — APPROVED** [review]
