### PR TITLE
Initialize Runtime Options with default values when absent in the config file

### LINKED ISSUE #1675: [Bug]: Object reference not set to Instance of an object
### What happened?

I am getting the following error when running data-api-builder via the SWA dev server:

```
[dataApi] fail: Azure.DataApiBuilder.Service.Startup[0]
[dataApi]       Unable to complete runtime initialization. Refer to exception for error details.
[dataApi]       System.NullReferenceException: Object reference not set to an instance of an object.
[dataApi]          at Azure.DataApiBuilder.Core.Configurations.RuntimeConfigValidator.ValidateGlobalEndpointRouteConfig(RuntimeConfig runtimeConfig) in /_/src/Core/Configurations/RuntimeConfigValidator.cs:line 336
[dataApi]          at Azure.DataApiBuilder.Core.Configurations.RuntimeConfigValidator.ValidateConfig() in /_/src/Core/Configurations/RuntimeConfigValidator.cs:line 75
[dataApi]          at Azure.DataApiBuilder.Service.Startup.PerformOnConfigChangeAsync(IApplicationBuilder app) in /_/src/Service/Startup.cs:line 565
[dataApi] fail: Azure.DataApiBuilder.Service.Startup[0]
[dataApi]       Exiting the runtime engine...
[dataApi] crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
[dataApi]       Application startup exception
[dataApi]       System.ApplicationException: Could not initialize the engine with the runtime config file: staticwebapp.database.config.json
[dataApi]          at Azure.DataApiBuilder.Service.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, RuntimeConfigProvider runtimeConfigProvider) in /_/src/Service/Startup.cs:line 306
[dataApi]          at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
[dataApi]          at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[dataApi]          at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
[dataApi]          at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
[dataApi]          at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
[dataApi]          at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
[dataApi]          at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
[dataApi]          at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
[dataApi] Unable to launch the runtime due to: System.ApplicationException: Could not initialize the engine with the runtime config file: staticwebapp.database.config.json
```
This just broke this morning. I noticed that SWA was downloading a new version of DAB and I wonder if that was what caused the issue?

My config file hasn't changed recently, here it is:
```
{
  "$schema": "https://github.com/Azure/data-api-builder/releases/download/v0.7.6/dab.draft.schema.json",
  "data-source": {
    "database-type": "cosmosdb_nosql",
    "options": {
      "database": "teaching-study",
      "schema": "staticwebapp.database.schema.gql"
    },
    "connection-string": "@env('DATABASE_CONNECTION_STRING')"
  },
  "runtime": {
    "graphql": {
      "allow-introspection": true,
      "enabled": true,
      "path": "/graphql"
    },
    "host": {
      "mode": "production",
      "cors": {
        "origins": [],
        "allow-credentials": false
      },
      "authentication": {
        "provider": "StaticWebApps"
      }
    }
  },
  "entities": {
    "Person": {
      "source": "participant-container",
      "permissions": [
        {
          "actions": ["create", "update", "read"],
          "role": "anonymous"
        }
      ]
    },
    "Submission": {
      "source": "submission-container",
      "permissions": [
        {
          "actions": ["create"],
          "role": "anonymous"
        }
      ]
    },
    "Questionnaire": {
      "source": "questionnaire-container",
      "permissions": [
        {
          "actions": ["create"],
          "role": "anonymous"
        }
      ]
    }
  }
}
```

### Version

0.8.49

### What database are you using?

CosmosDB NoSQL

### What hosting model are you using?

Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

GraphQL

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by severussundar**
## Why make this change?

- Closes #1675 
  - For Cosmos DB NoSQL database type, DAB CLI v0.8.49 generates a REST property within the Runtime section of the config file. However v0.7.6 does not generate this property. So, when the config file generated using v0.7.6 is used to start the engine with v0.8.49, the absence of the REST property causes the engine to throw exceptions.

## What is this change?

 
- With `v0.8.49`, these values are assumed to have non-null values because the CLI explicitly writes out all the fields to the config files. So, `null` checks are not performed extensively in all the places.
- However, when a config file that is generated using `v0.7.6`  is used, it could be possible that some of the fields are `null`. The absence of `null` checks leads to `NullReferenceExceptions` in this case. 
- To avoid this, all the `Runtime` options - `Rest`, `GraphQL` and `Host` are initialized with default values when they are `null` after deserialization of the config file.

## How was this tested?

- [x] Existing Unit Tests and Integration Tests
- [x] Manual Tests

# Sample Requests

- Database Type: Cosmos DB NoSQL
- Config file (Runtime section):
```json
 "runtime": {
    "graphql": {
      "enabled": true,
      "path": "/graphql",
      "allow-introspection": true
    },
    "host": {
      "cors": {
        "origins": [
          "http://localhost:5000"
        ],
        "allow-credentials": false
      },
      "authentication": {
        "provider": "StaticWebApps"
      },
      "mode": "development"
    }
  }
```
- Engine starts successfully:
image

- GraphQL Requests work successfully:
image

image

Note: This PR is directly targeted towards `release/0.8` branch (and the branch to make these changes was snapped off of `release/0.8`) because the current `main` has additional changes that are related to `0.9` and porting it over to `release/0.8` branch might not be possible.

### CODE REVIEW

File: src/Config/RuntimeConfigLoader.cs [hunk 1]
```diff
@@ -64,6 +64,32 @@ public RuntimeConfigLoader(string? connectionString = null)
             {
                 config = config with { DataSource = config.DataSource with { ConnectionString = connectionString } };
             }
+
+            // For Cosmos DB NoSQL database type, DAB CLI v0.8.49 generates a REST property within the Runtime section of the config file. However
```
Comment (abhishekkumams) [inline src/Config/RuntimeConfigLoader.cs:68]: this version details should not be a part of comment/ code summary

**Review by abhishekkumams — APPROVED** [review]
Thanks for investigating and adding the fix.

File: src/Config/RuntimeConfigLoader.cs (hunk 1 above)
Comment (Aniruddh25) [inline src/Config/RuntimeConfigLoader.cs:68]:
```suggestion
            // For Cosmos DB NoSQL database type, DAB CLI v0.8.49+ generates a REST property within the Runtime section of the config file. However
```

File: src/Config/RuntimeConfigLoader.cs [hunk 2]
```diff
@@ -64,6 +64,32 @@ public RuntimeConfigLoader(string? connectionString = null)
...
+            // v0.7.6 does not generate this property. So, when the config file generated using v0.7.6 is used to start the engine with v0.8.49, the absence
```
Comment (Aniruddh25) [inline src/Config/RuntimeConfigLoader.cs:69]:
```suggestion
            // v0.7.6- does not generate this property. So, when the config file generated using v0.7.6 is used to start the engine with v0.8.49+, the absence
```

File: src/Config/RuntimeConfigLoader.cs (hunk 1 above)
Comment (Aniruddh25) [reply src/Config/RuntimeConfigLoader.cs:68]: I modified it to be more generic with +/- attributes.

**Review by Aniruddh25 — APPROVED** [review]
Thanks for fixing this so soon.
