### PR TITLE
fix init command with environment variable

### LINKED ISSUE #1527: [Bug]: DAB init doesn't honor DAB_ENVIRONMENT variable
### What happened?

when `dab init` is called with environment variable `DAB_ENVIRONMENT=Development`. It should create a file with name `dab-config.Development.json`. Currently, it's only creating file dab-config.json

Although it does error out if dab-config.Development.json is already present, but if not present it should create this file.
image

### Version

running from main

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

_No response_

### Relevant log output

```Text
PS C:\myDir\dab-testing\latest-test> dab init --database-type mssql
Information: Microsoft.DataApiBuilder 1.0.0+e1bf19cc334b19534a30ab5f70274bba4bd81e24
Information: Config not provided. Trying to get default config based on DAB_ENVIRONMENT...
Information: Environment variable DAB_ENVIRONMENT is Development
Unable to find config file: dab-config.Development.json does not exist.
Found config file: dab-config.json.
Error: Config file: dab-config.json already exists. Please provide a different name or remove the existing config file.
Error: Could not generate config file.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by abhishekkumams**
## Why make this change?

- Closes #1527 
  - dab init doesn't create file with the environment Value, and always create default config if not specified explicitly.
  - For ex: if DAB_ENVIRONMENT is set to Development, it should create dab-config.Development.json, which is not the case.

## What is this change?

- Updating the logic to create config file giving precedence to environment value, also making sure error is thrown if the file is not present already.

## How was this tested?

- [X] Unit Tests

## Sample Request(s)

`dab init --database-type mssql`
above command will create:
1. DAB_ENVIRONMENT = null
dab-config.json
2. DAB_ENVIRONMENT = Development
dab-config.Development.json

### CODE REVIEW

File: src/Cli/ConfigGenerator.cs [hunk 1]
```diff
@@ -32,24 +32,35 @@ public class ConfigGenerator
         /// </summary>
         public static bool TryGenerateConfig(InitOptions options)
         {
-            if (!TryGetConfigFileBasedOnCliPrecedence(options.Config, out string runtimeConfigFile))
+            string runtimeConfigFile = RuntimeConfigPath.DefaultName;
+            string? environmentValue = Environment.GetEnvironmentVariable(RuntimeConfigPath.RUNTIME_ENVIRONMENT_VAR_NAME);
```
Comment (Aniruddh25) [inline src/Cli/ConfigGenerator.cs:36]: Can we GetEnvironmentVariable in the else?
This saves us 1 call if user already provides a config file

File: src/Cli.Tests/ConfigGeneratorTests.cs [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+    }
+
+    /// <summary>
+    /// Tests that environment config file is successfully generated when that file is not already present.
+    /// When environment variable is not set, it should generate the default config file.
+    /// </summary>
+    [DataTestMethod]
+    [DataRow(true, false, "Test", "dab-config.Test.json", DisplayName = "Failed to generate the config file when environment config file is present.")]
+    [DataRow(false, true, "Test", "dab-config.Test.json", DisplayName = "Successfully generated the config file when environment config file is not present.")]
+    [DataRow(false, true, "", "dab-config.json", DisplayName = "Successfully generated the config file when environment config file is not present and environment variable is not set.")]
```
Comment (Aniruddh25) [inline src/Cli.Tests/ConfigGeneratorTests.cs:51]: Isnt the last DataRow already being tested by other tests:

`Successfully generated the config file when environment config file is not present and environment variable is not set.`

File: src/Cli.Tests/ConfigGeneratorTests.cs [hunk 3]
```diff
@@ -0,0 +1,103 @@
...
+    public void TryGenerateConfig_UsingEnvironmentVariable(
+        bool isConfigFilePresentAlready,
+        bool isConfigGenerationSuccessful,
+        string environmentValue,
+        string configFileName)
+    {
+        Environment.SetEnvironmentVariable(RUNTIME_ENVIRONMENT_VAR_NAME, environmentValue);
+        HandleConfigFileCreationAndDeletion(configFileName, isConfigFilePresentAlready);
```
Comment (Aniruddh25) [inline src/Cli.Tests/ConfigGeneratorTests.cs:59]: What would happen if this test and the above test run in parallel? would the file creation/deletion interfere with each other?

File: src/Cli/ConfigGenerator.cs [hunk 4]
```diff
@@ -32,24 +32,35 @@ public class ConfigGenerator
...
+            if (!string.IsNullOrWhiteSpace(options.Config))
+            {
+                _logger.LogInformation("Generating user provided config file: {configFileName}", options.Config);
```
Comment (seantleonard) [inline src/Cli/ConfigGenerator.cs:39]:
```suggestion
                _logger.LogInformation("Generating user provided config file path: {configFileName}", options.Config);
```

either add path or name.. otherwise it reads as if the user is providing the actual file

File: src/Cli/ConfigGenerator.cs [hunk 5]
```diff
@@ -32,24 +32,35 @@ public class ConfigGenerator
...
-                    "Please provide a different name or remove the existing config file.");
+                _logger.LogError("Config file: {configFileName} already exists. Please provide a different name or remove the existing config file.", runtimeConfigFile);
                 return false;
             }
 
             // Creating a new json file with runtime configuration
             if (!TryCreateRuntimeConfig(options, out string runtimeConfigJson))
             {
-                _logger.LogError($"Failed to create the runtime config file.");
+                _logger.LogError("Failed to create the runtime config file.");
```
Comment (seantleonard) [inline src/Cli/ConfigGenerator.cs:63]: This error message seems inaccurate. There was a failure creating the runtime config with the provided options.

Failure to create the runtime config file is already logged in `Utils.WriteJsonContentToFile(fileName, configJson)`
Additionally, that same utils function may benefit from logging "successfully created config file {configFileName}" where the file name is the FULL path, which would help in debugging.

File: src/Cli/ConfigGenerator.cs [hunk 6]
```diff
@@ -32,24 +32,35 @@ public class ConfigGenerator
...
-                _logger.LogInformation($"Creating a new config file: {runtimeConfigFile}");
+                _logger.LogInformation("Generating default config file: {config}", runtimeConfigFile);
             }
 
             // File existence checked to avoid overwriting the existing configuration.
             if (File.Exists(runtimeConfigFile))
             {
-                _logger.LogError($"Config file: {runtimeConfigFile} already exists. " +
-                    "Please provide a different name or remove the existing config file.");
+                _logger.LogError("Config file: {configFileName} already exists. Please provide a different name or remove the existing config file.", runtimeConfigFile);
```
Comment (seantleonard) [inline src/Cli/ConfigGenerator.cs:56]: This would also benefit from logging the full path of the file name to assist with debugging. If dab cli installed via Nuget, it may not be immediately obvious where the config file is saved if user doesn't provide a full path.

File: src/Config/RuntimeConfigPath.cs [hunk 7]
```diff
@@ -233,6 +233,11 @@ private static string GetOverriddenName(string fileName)
             return $"{fileName}.overrides{CONFIG_EXTENSION}";
         }
 
+        public static string GetEnvironmentFileName(string fileName, string environmentValue)
```
Comment (seantleonard) [inline src/Config/RuntimeConfigPath.cs:236]: in a method comment, can you note that fileName must not include an extension? i.e. not `myConfig.json`

File: src/Cli.Tests/TestHelper.cs [hunk 8]
```diff
@@ -1133,5 +1133,25 @@ public static void SetupTestLoggerForCLI()
...
+            return new(
+                databaseType: DatabaseType.mssql,
+                connectionString: "testconnectionstring",
+                cosmosNoSqlDatabase: null,
+                cosmosNoSqlContainer: null,
+                graphQLSchemaPath: null,
+                setSessionContext: true,
+                hostMode: HostModeType.Development,
+                corsOrigin: new List<string>(),
+                authenticationProvider: EasyAuthType.StaticWebApps.ToString(),
```
Comment (seantleonard) [inline src/Cli.Tests/TestHelper.cs:1153]: Do other sample configs also set the authentication provider to `StaticWebApps`?

File: src/Cli.Tests/ConfigGeneratorTests.cs [hunk 9]
```diff
@@ -0,0 +1,103 @@
...
+    }
+
+    /// <summary>
+    /// Tests that user provided config file is successfully generated when that file is not already present.
+    /// </summary>
+    [DataTestMethod]
+    [DataRow(true, false, DisplayName = "Failed to generate config file when user provided config file is present.")]
+    [DataRow(false, true, DisplayName = "Successfully generated config file when user provided config file is not present.")]
+    public void TryGenerateConfig_WithUserProvidedConfig(
+        bool isConfigFilePresentAlready,
```
Comment (seantleonard) [inline src/Cli.Tests/ConfigGeneratorTests.cs:28]:
```suggestion
        bool isConfigFilePresent,
```

File: src/Cli.Tests/ConfigGeneratorTests.cs [hunk 10]
```diff
@@ -0,0 +1,103 @@
...
+        string environmentValue,
+        string configFileName)
+    {
+        Environment.SetEnvironmentVariable(RUNTIME_ENVIRONMENT_VAR_NAME, environmentValue);
+        HandleConfigFileCreationAndDeletion(configFileName, isConfigFilePresentAlready);
+        Assert.AreEqual(isConfigFilePresentAlready, File.Exists(configFileName));
+
+        InitOptions options = CreateBasicInitOptionsForMsSqlWithConfig();
+
+        Assert.AreEqual(isConfigGenerationSuccessful, ConfigGenerator.TryGenerateConfig(options));
```
Comment (seantleonard) [inline src/Cli.Tests/ConfigGeneratorTests.cs:64]: To explicitly validate that `ConfigGenerator.TryGenerateConfig(options)` failed because the specified file already exists, would you be able to validate that the ilogger logged ~~"Config file: {configFileName} already exists."

File: src/Cli.Tests/ConfigGeneratorTests.cs [hunk 11]
```diff
@@ -0,0 +1,103 @@
...
+    [DataRow(true, false, "Test", "dab-config.Test.json", DisplayName = "Failed to generate the config file when environment config file is present.")]
+    [DataRow(false, true, "Test", "dab-config.Test.json", DisplayName = "Successfully generated the config file when environment config file is not present.")]
+    [DataRow(false, true, "", "dab-config.json", DisplayName = "Successfully generated the config file when environment config file is not present and environment variable is not set.")]
+    public void TryGenerateConfig_UsingEnvironmentVariable(
+        bool isConfigFilePresentAlready,
+        bool isConfigGenerationSuccessful,
+        string environmentValue,
+        string configFileName)
+    {
+        Environment.SetEnvironmentVariable(RUNTIME_ENVIRONMENT_VAR_NAME, environmentValue);
```
Comment (seantleonard) [inline src/Cli.Tests/ConfigGeneratorTests.cs:58]: Can you remind me whether `RUNTIME_ENVIRONMENT_VAR_NAME` is guaranteed to be set in production / customer environments, and set by which mechanism? If we can't guarantee the present of the key `DAB_ENVIRONMENT`, are there tests covering scenarios where the env var key is not even present (and not just empty)?

File: src/Cli.Tests/ConfigGeneratorTests.cs [hunk 12]
```diff
@@ -0,0 +1,103 @@
...
+    public static void CleanUp()
+    {
+        if (File.Exists("dab-config.Test.json"))
+        {
+            File.Delete("dab-config.Test.json");
+        }
+
+        if (File.Exists("dab-config.json"))
+        {
+            File.Delete("dab-config.json");
```
Comment (seantleonard) [inline src/Cli.Tests/ConfigGeneratorTests.cs:100]: You don't need the existence check in `File.Delete(file)`: "If the file to be deleted does not exist, no exception is thrown." https://learn.microsoft.com/en-us/dotnet/api/system.io.file.delete?view=net-7.0#remarks

File: src/Cli.Tests/ConfigGeneratorTests.cs [hunk 13]
```diff
@@ -0,0 +1,103 @@
...
+            Assert.AreEqual(isConfigGenerationSuccessful, File.Exists(configFileName));
+        }
+    }
+
+    /// <summary>
+    /// This method handles the creation and deletion of a configuration file.
+    /// </summary>
+    private static void HandleConfigFileCreationAndDeletion(string configFilePath, bool configFilePresent)
+    {
+        if (File.Exists(configFilePath) && !configFilePresent)
```
Comment (seantleonard) [inline src/Cli.Tests/ConfigGeneratorTests.cs:76]: This could be simplified given the behavior of File.Delete mentioned in another comment.

File: src/Cli.Tests/ConfigGeneratorTests.cs [hunk 14]
```diff
@@ -0,0 +1,103 @@
...
+        {
+            File.Delete(configFilePath);
+        }
+        else if (!File.Exists(configFilePath) && configFilePresent)
+        {
+            File.Create(configFilePath).Dispose();
+        }
```
Comment (seantleonard) [inline src/Cli.Tests/ConfigGeneratorTests.cs:83]: Could this be simplified given that File.Create overwrites the file if it already exists?

File: src/Cli.Tests/EndToEndTests.cs [hunk 15]
```diff
@@ -18,7 +18,12 @@ public static void Setup(TestContext context)
     {
         if (!File.Exists(TEST_SCHEMA_FILE))
         {
-            File.Create(TEST_SCHEMA_FILE);
+            File.Create(TEST_SCHEMA_FILE).Dispose();
+        }
+
+        if (File.Exists(TEST_RUNTIME_CONFIG_FILE))
+        {
+            File.Delete(TEST_RUNTIME_CONFIG_FILE);
```
Comment (seantleonard) [inline src/Cli.Tests/EndToEndTests.cs:26]: Could this be simplified given File.Delete behavior? also, is it desireable to create the file during every classInitialize because pre-existing file may lead to unintended side effects?

**Review by seantleonard — CHANGES_REQUESTED** [review]
Some questions and suggestions for simplification

File: src/Cli.Tests/TestHelper.cs (hunk 8 above)
Comment (abhishekkumams) [reply src/Cli.Tests/TestHelper.cs:1115]: Yep, all the test configs use `StaticWebApps`

File: src/Cli/ConfigGenerator.cs (hunk 1 above)
Comment (abhishekkumams) [reply src/Cli/ConfigGenerator.cs]: we need the value before that since we are validating the condition in elseif

File: src/Cli.Tests/ConfigGeneratorTests.cs (hunk 2 above)
Comment (abhishekkumams) [reply src/Cli.Tests/ConfigGeneratorTests.cs:65]: yep, right. Thanks for flagging.

File: src/Cli/ConfigGenerator.cs (hunk 5 above)
Comment (abhishekkumams) [reply src/Cli/ConfigGenerator.cs:67]: using the Utils method for logs, and removing extra logs here.

File: src/Cli.Tests/ConfigGeneratorTests.cs (hunk 11 above)
Comment (abhishekkumams) [reply src/Cli.Tests/ConfigGeneratorTests.cs:72]: NO, it's guaranteed to be set, and it can be set by directly logging into the console of the production system. Added a test to cover that

File: src/Cli.Tests/ConfigGeneratorTests.cs (hunk 10 above)
Comment (abhishekkumams) [reply src/Cli.Tests/ConfigGeneratorTests.cs]: added validation for logger message

File: src/Cli.Tests/ConfigGeneratorTests.cs (hunk 3 above)
Comment (abhishekkumams) [reply src/Cli.Tests/ConfigGeneratorTests.cs]: In C#, by default, the  TestMethod  under a  TestClass  does not run in parallel. Each test method is executed sequentially, one after another. This default behavior ensures that each test is executed in isolation and avoids any potential interference between test cases. 
Although we can parallelize it by using `[Parallelize]` attribute.

**Review by seantleonard — APPROVED** [review]
Thanks for fixing! also for addressing comment, very clean. Appreciate the ability to see full file path in the logs, will help us/PMs/customers troubleshoot if necessary!

File: src/Cli/ConfigGenerator.cs (hunk 1 above)
Comment (Aniruddh25) [reply src/Cli/ConfigGenerator.cs]: We could write the else as 

```
else
{
envValue =  GetEnvironmentVariable()
 if (envValue)
}
```

Comment (abhishekkumams) [reply src/Cli/ConfigGenerator.cs]: but we have another else as well, which should only execute when the above two conditions are not met.

File: src/Cli/ConfigGenerator.cs [hunk 16]
```diff
@@ -36,23 +36,38 @@ public class ConfigGenerator
...
+                    _logger.LogInformation("Generating default config file: {config}", Path.GetFullPath(runtimeConfigFile));
+                }
             }
 
             // File existence checked to avoid overwriting the existing configuration.
             if (fileSystem.File.Exists(runtimeConfigFile))
             {
-                _logger.LogError("Config file: {runtimeConfigFile} already exists. Please provide a different name or remove the existing config file.", runtimeConfigFile);
+                _logger.LogError("Config file: {runtimeConfigFile} already exists. Please provide a different name or remove the existing config file.",
+                    Path.GetFullPath(runtimeConfigFile));
```
Comment (Aniruddh25) [inline src/Cli/ConfigGenerator.cs:64]: What if Path.GetFullPath throws exception?

File: src/Config/RuntimeConfigLoader.cs [hunk 17]
```diff
@@ -230,6 +230,15 @@ private static string GetOverriddenName(string fileName)
         return $"{fileName}.overrides{CONFIG_EXTENSION}";
     }
 
+    /// <summary>
+    /// Generates the name of the file based on environment value.
+    /// NOTE: Input File name should not contain extension
```
Comment (Aniruddh25) [inline src/Config/RuntimeConfigLoader.cs:235]: What if it contains the file extension name? How would the end user know NOT to provide the extension? 

Can we be flexible? Check for json extension at the end, if not present add it?

**Review by Aniruddh25 — APPROVED** [review]
LGTM, after fixing some corner cases.

File: src/Cli/ConfigGenerator.cs (hunk 16 above)
Comment (aaronpowell) [reply src/Cli/ConfigGenerator.cs:64]: We should be using `fileSystem.Path` not `Path` directly to ensure we're working against the right file system.

**Review by aaronpowell — DISMISSED** [review]

File: src/Config/RuntimeConfigLoader.cs (hunk 17 above)
Comment (abhishekkumams) [reply src/Config/RuntimeConfigLoader.cs:235]: This method is not invoked by user. It's an internal method which is invoked when a default scenario is triggered.
The comment is intended for developers who would may want to reuse this method for other purposes.
