### PR TITLE
 Verifying the read access of anonymous users prior to transmitting the Mutation result.

### LINKED ISSUE #1464: GraphQL - Roles defined without read action returns error
When a role is defined without `read` action, mutations performed in the context of that role, returns an error response. However, at the database level, the mutation(update,insert, etc. action) succeeds. 

Repro steps:
1) In the config file available in the main branch, remove the `read` action for the `Anonymous` role
2) Execute the following mutation request in the context of `Anonymous` role

```graphql
mutation {
     updatebook(id: 1, item: {title: "Harry Potter and the Goblet of Fire"}){
          id
          title
     }
}
```

Mutation - Read role not defined bug

This scenario needs to be better handled.
a) For roles defined without read action, only graphQL special field `__typename` could be allowed. Other entity fields can be disallowed in the selection set.
b) Behavior needs to be better documented.

### PR DESCRIPTION
**Pull request by neeraj-sharma2592**
## Why make this change?
Resolves #1464 for CosmosDB.

## What is this change?
Verifying the read access of anonymous users prior to transmitting the Mutation result

## How was this tested?

- [X] Integration Tests

### CODE REVIEW

**Review by severussundar — COMMENTED** [review]
Need to add tests. After feedback, the format of the error message is slightly changed to include the mutation operation name as well. Please refer to [this PR](https://github.com/Azure/data-api-builder/pull/1874) for the latest format

File: src/Core/Resolvers/CosmosMutationEngine.cs [hunk 1]
```diff
@@ -233,6 +235,14 @@ private static async Task<ItemResponse<JObject>> HandleUpdateAsync(IDictionary<s
             }
         }
 
+        private void CheckReadAccess(string entityName)
+        {
+            if (!_authorizationResolver.AreRoleAndOperationDefinedForEntity(entityName, AuthorizationType.Anonymous.ToString(), EntityActionOperation.Read))
+            {
+                throw new Exception("The database operation was successful but the current user is unable to view the response due to lack of read permissions");
+            }
+        }
```
Comment (seantleonard) [inline src/Core/Resolvers/CosmosMutationEngine.cs:244]: Why hardcoding to `AuthorizationType.Anonymous`? 

You should be acquiring the current role from the GraphQL execution context. See `AuthorizeMutationFields(...)` which has a snippet that you can use.

**Review by seantleonard — CHANGES_REQUESTED** [review]
need tests too. @neeraj-sharma2592

File: src/Core/Resolvers/CosmosMutationEngine.cs [hunk 2]
```diff
@@ -233,6 +235,14 @@ private static async Task<ItemResponse<JObject>> HandleUpdateAsync(IDictionary<s
             }
         }
 
+        private void CheckReadAccess(string entityName)
```
Comment (abhishekkumams) [inline src/Core/Resolvers/CosmosMutationEngine.cs:238]: Add Summary for the function

File: src/Service.Tests/CosmosTests/MutationTests.cs [hunk 3]
```diff
@@ -390,6 +402,246 @@ public async Task UpdateMutationWithOnlyTypenameInSelectionSet()
...
+
+        /// <summary>
+        /// For mutation operations, the respective mutation operation type(create/update/delete) + read permissions are needed to receive a valid response.
+        /// For graphQL requests, if read permission is configured for Anonymous role, then it is inherited by other roles.
+        /// In this test, Anonymous role has read permission configured. Authenticated role has only create permission configured.
+        /// A create mutation operation is executed in the context of Authenticated role and the response is expected to have no errors because
+        /// the read permission is inherited from Anonymous role.
+        /// </summary>
+        [TestMethod]
+        [TestCategory(TestCategory.MSSQL)]
```
Comment (severussundar) [inline src/Service.Tests/CosmosTests/MutationTests.cs:546]: nit: TestCategory is incorrect. 

Can be removed as the test category is already defined at the class level

File: src/Service.Tests/CosmosTests/MutationTests.cs [hunk 4]
```diff
@@ -2,13 +2,25 @@
...
+using Azure.DataApiBuilder.Core.Configurations;
 using Azure.DataApiBuilder.Core.Resolvers;
 using Azure.DataApiBuilder.Service.Exceptions;
+using Azure.DataApiBuilder.Service.Tests.Configuration;
+using Microsoft.AspNetCore.TestHost;
 using Microsoft.Azure.Cosmos;
 using Microsoft.Extensions.DependencyInjection;
+using Microsoft.OData.UriParser;
 using Microsoft.VisualStudio.TestTools.UnitTesting;
+using Sprache;
```
Comment (severussundar) [inline src/Service.Tests/CosmosTests/MutationTests.cs:23]: It could be worth double checking if any of the functions from this library is being used?

File: src/Core/Resolvers/CosmosMutationEngine.cs [hunk 5]
```diff
@@ -258,6 +273,29 @@ private static async Task<ItemResponse<JObject>> HandleUpdateAsync(IDictionary<s
...
         }
 
+        /// <summary>
+        /// Helper method to get the role with which the GraphQL API request was executed.
+        /// </summary>
+        /// <param name="context">HotChocolate context for the GraphQL request</param>
+        private static string GetRoleOfGraphQLRequest(IMiddlewareContext context)
+        {
+            string role = string.Empty;
+            if (context.ContextData.TryGetValue(key: AuthorizationResolver.CLIENT_ROLE_HEADER, out object? value) && value is StringValues stringVals)
```
Comment (severussundar) [inline src/Core/Resolvers/CosmosMutationEngine.cs:283]: `AuthorizeMutationFields()` method already contains logic to extract the role. For SQL, I refactored the logic for extracting the role from graphQL context to a separate helper function. It could be worth checking if that can be re-used here.

**Review by severussundar — CHANGES_REQUESTED** [review]
Looks good for the most part. Some suggestions around re-using helper functions and few nits in tests

File: src/Core/Resolvers/CosmosMutationEngine.cs (hunk 5 above)
Comment (neeraj-sharma2592) [reply src/Core/Resolvers/CosmosMutationEngine.cs:283]: Sure. I'll check that

Comment (neeraj-sharma2592) [reply src/Core/Resolvers/CosmosMutationEngine.cs:283]: I examined the AuthorizeMutationFields, and it indeed retrieves the role. While I could store that information in a global variable and access it within my scenario, I believe that approach might not be clean and may not effectively communicate the intention behind the change. I am more inclined to obtain the role from this helper function. Thoughts?

File: src/Core/Resolvers/CosmosMutationEngine.cs [hunk 6]
```diff
@@ -74,6 +74,21 @@ private async Task<JObject> ExecuteAsync(IMiddlewareContext context, IDictionary
                 _ => throw new NotSupportedException($"unsupported operation type: {resolver.OperationType}")
             };
 
+            string roleName = GetRoleOfGraphQLRequest(context);
+
+            // The presence of READ permission is checked in the current role (with which the request is executed) as well as Anonymous role. This is because, for GraphQL requests,
+            // READ permission is inherited by other roles from Anonymous role when present.
+            bool isReadPermissionConfigured = _authorizationResolver.AreRoleAndOperationDefinedForEntity(entityName, roleName, EntityActionOperation.Read)
+                                              || _authorizationResolver.AreRoleAndOperationDefinedForEntity(entityName, AuthorizationType.Anonymous.ToString(), EntityActionOperation.Read);
```
Comment (seantleonard) [inline src/Core/Resolvers/CosmosMutationEngine.cs:82]:
```suggestion
                                              || _authorizationResolver.AreRoleAndOperationDefinedForEntity(entityName, AuthorizationResolver.ROLE_ANONYMOUS, EntityActionOperation.Read);
```

File: src/Core/Resolvers/CosmosMutationEngine.cs (hunk 5 above)
Comment (seantleonard) [reply src/Core/Resolvers/CosmosMutationEngine.cs:283]: `AuthorizeMutationFields()` should be updated to now call `GetRoleOfGraphQLRequest()` to eliminate code duplication.

File: src/Service.Tests/CosmosTests/MutationTests.cs [hunk 7]
```diff
@@ -390,6 +399,245 @@ public async Task UpdateMutationWithOnlyTypenameInSelectionSet()
...
+                    JsonElement queryResponse = await GraphQLRequestExecutor.PostGraphQLRequestAsync(
+                                                client,
+                                                server.Services.GetRequiredService<RuntimeConfigProvider>(),
+                                                query: graphQLQuery,
+                                                queryName: queryName,
+                                                variables: null,
+                                                authToken: authToken,
+                                                clientRoleHeader: AuthorizationResolver.ROLE_AUTHENTICATED);
+
+                    Assert.IsFalse(queryResponse.TryGetProperty("errors", out _));
```
Comment (seantleonard) [inline src/Service.Tests/CosmosTests/MutationTests.cs:517]: can you add param `message` with a value something like:  `message: "The response was not expected to have errors."`

File: src/Service.Tests/CosmosTests/MutationTests.cs [hunk 8]
```diff
@@ -390,6 +399,245 @@ public async Task UpdateMutationWithOnlyTypenameInSelectionSet()
...
+                        client,
+                        server.Services.GetRequiredService<RuntimeConfigProvider>(),
+                        query: _createPlanetMutation,
+                        queryName: "createPlanet",
+                        variables: new() { { "item", input } },
+                        authToken: AuthTestHelper.CreateStaticWebAppsEasyAuthToken(),
+                        clientRoleHeader: AuthorizationResolver.ROLE_AUTHENTICATED
+                        );
+                        
+                    Assert.IsFalse(mutationResponse.TryGetProperty("errors", out _));
```
Comment (seantleonard) [inline src/Service.Tests/CosmosTests/MutationTests.cs:624]: can you add param `message` with a value something like:  `message: "The response was not expected to have errors."`

File: src/Service.Tests/CosmosTests/MutationTests.cs [hunk 9]
```diff
@@ -390,6 +399,245 @@ public async Task UpdateMutationWithOnlyTypenameInSelectionSet()
...
+                    JsonElement mutationResponse = await GraphQLRequestExecutor.PostGraphQLRequestAsync(
+                        client,
+                        server.Services.GetRequiredService<RuntimeConfigProvider>(),
+                        query: _createPlanetMutation,
+                        queryName: "createPlanet",
+                        variables: new() { { "item", input } },
+                        clientRoleHeader: null
+                        );
+
+                    Assert.IsTrue(mutationResponse.ToString().Contains("The mutation operation createPlanet was successful but the current user is unauthorized to view the response due to lack of read permissions"));
```
Comment (seantleonard) [inline src/Service.Tests/CosmosTests/MutationTests.cs:495]: can you add param `message` with a value something like:  `message: "The response was not expected to have errors."`

File: src/Service.Tests/CosmosTests/MutationTests.cs [hunk 10]
```diff
@@ -390,6 +399,245 @@ public async Task UpdateMutationWithOnlyTypenameInSelectionSet()
...
+        ///
+        /// A create mutation operation in the context of Anonymous role is executed and the expected error message is validated.
+        /// Authenticated role has read permission configured. A pk query is executed in the context of Authenticated role to validate that a new
+        /// record was created in the database.
+        /// </summary>
+        [TestMethod]
+        public async Task ValidateErrorMessageForMutationWithoutReadPermission()
+        {
+            const string SCHEMA = @"
+type Planet @model {
```
Comment (seantleonard) [inline src/Service.Tests/CosmosTests/MutationTests.cs:417]: please add value to `@model` directive per https://learn.microsoft.com/azure/data-api-builder/database-specific-features#user-provided-graphql-schema

File: src/Service.Tests/CosmosTests/MutationTests.cs [hunk 11]
```diff
@@ -390,6 +399,245 @@ public async Task UpdateMutationWithOnlyTypenameInSelectionSet()
...
+        /// For graphQL requests, if read permission is configured for Anonymous role, then it is inherited by other roles.
+        /// In this test, Anonymous role has read permission configured. Authenticated role has only create permission configured.
+        /// A create mutation operation is executed in the context of Authenticated role and the response is expected to have no errors because
+        /// the read permission is inherited from Anonymous role.
+        /// </summary>
+        [TestMethod]
+        public async Task ValidateInheritanceOfReadPermissionFromAnonymous()
+        {
+            const string SCHEMA = @"
+type Planet @model {
```
Comment (seantleonard) [inline src/Service.Tests/CosmosTests/MutationTests.cs:546]: please add value to `@model` directive per https://learn.microsoft.com/azure/data-api-builder/database-specific-features#user-provided-graphql-schema

**Review by severussundar — APPROVED** [review]
LGTM

**Review by seantleonard — APPROVED** [review]
thanks for updating with this behavior and addressing feedback!
