### PR TITLE
Fix optional Auth section issue

### LINKED ISSUE #2513: [Bug]: Upgrading to 1.3.19 breaks due to auth changes
### What happened?

Bringing https://github.com/CommunityToolkit/Aspire/issues/363 in from the Aspire Community Toolkit DAB integration.

The problem seems to be related to the changes in #2414 as it now requires an auth section to be defined in the DAB config, when it previously was optional.

### Version

1.3.19

### What database are you using?

Azure SQL

### What hosting model are you using?

Custom Docker host

### Which API approach are you accessing DAB through?

REST

### Relevant log output

```Text
2025-01-02T20:38:26 fail: Microsoft.AspNetCore.Server.Kestrel[13]
2025-01-02T20:38:26       Connection id "0HN9BCK3B00Q9", Request id "0HN9BCK3B00Q9:00000001": An unhandled exception was thrown by the application.
2025-01-02T20:38:26       System.InvalidOperationException: No authentication handler is registered for the scheme 'OAuthAuthentication'. The registered schemes are: StaticWebAppsAuthentication, Bearer, SimulatorAuthentication. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("OAuthAuthentication",...)?
2025-01-02T20:38:26          at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
2025-01-02T20:38:26          at Azure.DataApiBuilder.Core.AuthenticationHelpers.ClientRoleHeaderAuthenticationMiddleware.InvokeAsync(HttpContext httpContext) in /_/src/Core/AuthenticationHelpers/ClientRoleHeaderAuthenticationMiddleware.cs:line 76
2025-01-02T20:38:26          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2025-01-02T20:38:26          at Azure.DataApiBuilder.Service.Startup.<>c__DisplayClass15_0.<<Configure>b__3>d.MoveNext() in /_/src/Service/Startup.cs:line 374
2025-01-02T20:38:26       --- End of stack trace from previous location ---
2025-01-02T20:38:26          at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
2025-01-02T20:38:26          at Azure.DataApiBuilder.Core.Services.PathRewriteMiddleware.InvokeAsync(HttpContext httpContext) in /_/src/Core/Services/PathRewriteMiddleware.cs:line 89
2025-01-02T20:38:26          at Azure.DataApiBuilder.Core.Services.CorrelationIdMiddleware.Invoke(HttpContext httpContext) in /_/src/Core/Services/CorrelationIdMiddleware.cs:line 53
2025-01-02T20:38:26          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2025-01-02T20:38:30 fail: Microsoft.AspNetCore.Server.Kestrel[13]
2025-01-02T20:38:30       Connection id "0HN9BCK3B00Q9", Request id "0HN9BCK3B00Q9:00000002": An unhandled exception was thrown by the application.
2025-01-02T20:38:30       System.InvalidOperationException: No authentication handler is registered for the scheme 'OAuthAuthentication'. The registered schemes are: StaticWebAppsAuthentication, Bearer, SimulatorAuthentication. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("OAuthAuthentication",...)?
2025-01-02T20:38:30          at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
2025-01-02T20:38:30          at Azure.DataApiBuilder.Core.AuthenticationHelpers.ClientRoleHeaderAuthenticationMiddleware.InvokeAsync(HttpContext httpContext) in /_/src/Core/AuthenticationHelpers/ClientRoleHeaderAuthenticationMiddleware.cs:line 76
2025-01-02T20:38:30          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2025-01-02T20:38:30          at Azure.DataApiBuilder.Service.Startup.<>c__DisplayClass15_0.<<Configure>b__3>d.MoveNext() in /_/src/Service/Startup.cs:line 374
2025-01-02T20:38:30       --- End of stack trace from previous location ---
2025-01-02T20:38:30          at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
2025-01-02T20:38:30          at Azure.DataApiBuilder.Core.Services.PathRewriteMiddleware.InvokeAsync(HttpContext httpContext) in /_/src/Core/Services/PathRewriteMiddleware.cs:line 89
2025-01-02T20:38:30          at Azure.DataApiBuilder.Core.Services.CorrelationIdMiddleware.Invoke(HttpContext httpContext) in /_/src/Core/Services/CorrelationIdMiddleware.cs:line 53
2025-01-02T20:38:30          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2025-01-02T20:38:35 fail: Microsoft.AspNetCore.Server.Kestrel[13]
2025-01-02T20:38:35       Connection id "0HN9BCK3B00Q9", Request id "0HN9BCK3B00Q9:00000003": An unhandled exception was thrown by the application.
2025-01-02T20:38:35       System.InvalidOperationException: No authentication handler is registered for the scheme 'OAuthAuthentication'. The registered schemes are: StaticWebAppsAuthentication, Bearer, SimulatorAuthentication. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("OAuthAuthentication",...)?
2025-01-02T20:38:35          at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
2025-01-02T20:38:35          at Azure.DataApiBuilder.Core.AuthenticationHelpers.ClientRoleHeaderAuthenticationMiddleware.InvokeAsync(HttpContext httpContext) in /_/src/Core/AuthenticationHelpers/ClientRoleHeaderAuthenticationMiddleware.cs:line 76
2025-01-02T20:38:35          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2025-01-02T20:38:35          at Azure.DataApiBuilder.Service.Startup.<>c__DisplayClass15_0.<<Configure>b__3>d.MoveNext() in /_/src/Service/Startup.cs:line 374
2025-01-02T20:38:35       --- End of stack trace from previous location ---
2025-01-02T20:38:35          at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
2025-01-02T20:38:35          at Azure.DataApiBuilder.Core.Services.PathRewriteMiddleware.InvokeAsync(HttpContext httpContext) in /_/src/Core/Services/PathRewriteMiddleware.cs:line 89
2025-01-02T20:38:35          at Azure.DataApiBuilder.Core.Services.CorrelationIdMiddleware.Invoke(HttpContext httpContext) in /_/src/Core/Services/CorrelationIdMiddleware.cs:line 53
2025-01-02T20:38:35          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by abhishekkumams**
## Why make this change?

- Closes #2513
  - DAB engine was unable to process request successfully when an optional auth section in the config was not provided which introduced regression.

## What is this change?

- Updating the logic which selects the default Auth when not provided.
- New method  `ResolveConfiguredAuthNScheme` introduced PR: #2414, didn't have a case where no auth was provided. So it was going to the else condition which was choosing OAuth but this else section was only supposed to handle only non-out of box
authentication provider names supplied in dab-config.json

## How was this tested?

- [x] Integration Tests
- [x] Manual Tests

## Sample Request(s)

- Create a config and exclude the auth section
- was able to start and correctly execute requests

image

### CODE REVIEW

File: src/Core/AuthenticationHelpers/ClientRoleHeaderAuthenticationMiddleware.cs [hunk 1]
```diff
@@ -179,13 +179,14 @@ public static bool IsSystemRole(string roleName)
     /// <returns>Authentication Scheme</returns>
     private static string ResolveConfiguredAuthNScheme(string? configuredProviderName)
     {
-        if (string.Equals(configuredProviderName, SupportedAuthNProviders.APP_SERVICE, StringComparison.OrdinalIgnoreCase))
+        if (string.IsNullOrWhiteSpace(configuredProviderName)
+            || string.Equals(configuredProviderName, SupportedAuthNProviders.STATIC_WEB_APPS, StringComparison.OrdinalIgnoreCase))
         {
-            return EasyAuthAuthenticationDefaults.APPSERVICEAUTHSCHEME;
+            return EasyAuthAuthenticationDefaults.SWAAUTHSCHEME;
```
Comment (Aniruddh25) [inline src/Core/AuthenticationHelpers/ClientRoleHeaderAuthenticationMiddleware.cs:185]: Remind me, when there used to be no auth section - did we default to SWA?

**Review by Aniruddh25 — APPROVED** [review]
Thanks for verifying and pushing out the fix for this regression. Addition of the test will help us watch out for future such regressions.

**Review by sezal98 — COMMENTED** [review]
What would the situations for the final else scenario?

**Review by sezal98 — APPROVED** [review]

File: src/Core/AuthenticationHelpers/ClientRoleHeaderAuthenticationMiddleware.cs (hunk 1 above)
Comment (abhishekkumams) [reply src/Core/AuthenticationHelpers/ClientRoleHeaderAuthenticationMiddleware.cs:185]: yes

**Comment by abhishekkumams** [comment]
> What would the situations for the final else scenario?

when the user would use something out of the box not defined in DAB
