### PR TITLE
#3053 Fix by using custom bool parsing that if a string is found then…

### LINKED ISSUE #3053: [Bug]: Application Insights can't be disabled by environment variables
### What happened?

There is no environment variable substitution on booleans thus you can't enabled and disable telemetry by environment variables.

Requires significant hacks to work around this at startup in the docker container. 

### Version

1.6+

### What database are you using?

Azure SQL

### What hosting model are you using?

Container Apps

### Which API approach are you accessing DAB through?

REST

### Relevant log output

```Text
Error that config isn't valid
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by simonsabin**
… it uses the environment replacement and looks for a true false 1 or 0.

## Why make this change?

Fixes #3053 

Boolean values can't be set using environment variables. This allows that

## What is this change?

Using custom JsonConverter for bools that if a string is detected it uses the string serialiser that uses the environment replacement rules. 

## How was this tested?

- [ ] Integration Tests
- [x] Unit Tests

### CODE REVIEW

File: src/Config/Converters/BooleanJsonConverter.cs [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+using System.Text.Json;
+using System.Text.Json.Serialization;
+
+namespace Azure.DataApiBuilder.Config.Converters;
+
+/// <summary>
+/// Custom string json converter factory to replace environment variables and other variable patterns
+/// during deserialization using the DeserializationVariableReplacementSettings.
+/// </summary>
+public class BoolJsonConverter : JsonConverter<bool>
```
[the remark this answers is not in the document]
Comment (Aniruddh25) [reply src/Config/Converters/BooleanJsonConverter.cs:14]: If the filename was changed to ConverterFactory, the class name should be changed to BooleanJsonConverterFactory here as well.

File: src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs [hunk 2]
```diff
@@ -213,6 +213,71 @@ private static string GetExpectedPropertyValue(string envVarName, bool replaceEn
...
+                string configJson = @"{
+                    ""$schema"": ""https://github.com/Azure/data-api-builder/releases/download/vmajor.minor.patch-alpha/dab.draft.schema.json"",
+                    ""data-source"": {
+                        ""database-type"": ""mssql"",
+                        ""connection-string"": ""Server=tcp:127.0.0.1,1433;Persist Security Info=False;Trusted_Connection=True;TrustServerCertificate=True;MultipleActiveResultSets=False;Connection Timeout=5;""
+                    },
+                    ""runtime"": {
+                        ""telemetry"": {
+                            ""application-insights"": {
+                                ""enabled"": " + configValue + @",
```
Comment (Aniruddh25) [inline src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs:279]: Should there be a test for the configValue itself be in double quotes? So, 

`"enabled" : "true"` or
`"enabled" : "@env('application_insights_enabled')"`

Comment (Aniruddh25) [reply src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs:279]: Without this, the current test is not testing the scenario when configValue is hardcoded to true because this code will translate to `"enabled": true,`

Comment (simonsabin) [reply src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs:279]: putting a load more tests

File: src/Config/Converters/BooleanJsonConverter.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (Aniruddh25) [reply src/Config/Converters/BooleanJsonConverter.cs:14]: In reality, this is not a factory, So the file name should be kept as BoolJsonConverter to match the existing class name `BoolJsonConverter`

File: src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs [hunk 3]
```diff
@@ -213,6 +213,71 @@ private static string GetExpectedPropertyValue(string envVarName, bool replaceEn
...
+        [DataRow(true, true, DisplayName = "Config with enabled set to true ")]
+        [DataRow(true, false, DisplayName = "Config with enabled set to false")]
+        [DataRow(false, true,  DisplayName = "Replace environment variables containing boolean value with true")]
+        [DataRow(false, false, DisplayName = "Replace environment variables containing boolean value with false")]
+
+        public void TestTelemetryApplicationInsightsEnabledWithEnvironmentVariable(bool hardcoded, bool expected)
+        {
+            // Arrange
+            const string envVarName = "APP_INSIGHTS_ENABLED";
+             string envVarValue = expected.ToString();
```
[the remark this answers is not in the document]
Comment (simonsabin) [reply src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs]: Extra test cases have been added

File: src/Config/Converters/BooleanJsonConverter.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (simonsabin) [reply src/Config/Converters/BooleanJsonConverter.cs:14]: file renamed

File: src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs (hunk 2 above)
Comment (simonsabin) [reply src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs:279]: a whole set of extra tests to handle string and non string booleans

**Comment by simonsabin** [comment]
> Additional testing for double quoted value boolean value to test the string deserialization.

I think this is now catered for it you mean where the json is the following. 

```
{
 .... 
  "enabled": "true"
  ...
}
```
and also 
```
{
 .... 
   "enabled": true
  ...
}
```

File: src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs [hunk 4]
```diff
@@ -213,6 +213,71 @@ private static string GetExpectedPropertyValue(string envVarName, bool replaceEn
...
+                Assert.IsNotNull(runtimeConfig.Runtime.Telemetry.ApplicationInsights, "ApplicationInsights section should not be null");
+                Assert.AreEqual("InstrumentationKey=test-key", runtimeConfig.Runtime.Telemetry.ApplicationInsights.ConnectionString, "Connection string should be preserved");
+                Assert.AreEqual(expected, runtimeConfig.Runtime.Telemetry.ApplicationInsights.Enabled, "ApplicationInsights enabled value should match expected value");
+            }
+            finally
+            {
+                // Cleanup
+                Environment.SetEnvironmentVariable(envVarName, null);
+            }
+        }
```
[the remark this answers is not in the document]
Comment (simonsabin) [reply src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs]: extra test cases have been added

File: src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs (hunk 2 above)
Comment (simonsabin) [reply src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs:279]: test now check for true, false, 0, 1 natively, hardcoded within a string, or from an environment replacement. 
Assuming keyvault replacements would "just work"

**Comment by JerryNixon** [comment]
I am not sure this resolves JSON Schema constraints/editing errors, does it?

**Review by simonsabin — COMMENTED** [review]
> I am not sure this resolves JSON Schema constraints/editing errors, does it?

It doesn't but this would

**Comment by simonsabin** [comment]
> I am not sure this resolves JSON Schema constraints/editing errors, does it?

@JerryNixon  It doesn't but I've just pushed change to the schema that would. 

If thats an acceptable approach I can apply to other booleans.

Interestinlythere does seem to be a mix of json schema validation jsonconverter validation. The jsonconverter stuff looks overly complicated. for some simple serialisation.

**Comment by simonsabin** [comment]
Added tests to validate the schema approach.  for key enabled flags.

**Comment by simonsabin** [comment]
forgot formatting, try again

File: schemas/dab.draft.schema.json [hunk 5]
```diff
@@ -1391,7 +1391,15 @@
...
-          "required": ["singular"]
+          "required": [ "singular" ]
+        }
+      ]
+    },
+    "boolean-or-string": {
+      "oneOf":[
+        {
+          "type": [ "boolean", "string" ],
+          "pattern": "^(true|false|1|0|@env\\('.*'\\)|@akv\\('.*'\\))$"
```
Comment (JerryNixon) [inline schemas/dab.draft.schema.json]:
```suggestion
          "pattern": "^(?:true|false|1|0|@.{3}\\('.*'\\))$"
```

File: src/Config/Converters/BooleanJsonConverter.cs [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+/// other converters (for example, the string converter) before the value is parsed here.
+public class BoolJsonConverter : JsonConverter<bool>
+{
+
+    public override bool Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
+    {
+        if (reader.TokenType is JsonTokenType.Null)
+        {
+
+            throw new JsonException();
```
Comment (JerryNixon) [inline src/Config/Converters/BooleanJsonConverter.cs]:
```suggestion
            throw new JsonException("Unexpected null JSON token. Expected a boolean literal or a valid @expression.");
```

File: src/Config/Converters/BooleanJsonConverter.cs [hunk 7]
```diff
@@ -0,0 +1,61 @@
...
+                _ => throw new JsonException($"Invalid boolean value. Specify either true or false."),
+            };
+            return result;
+        }
+        else
+        {
+            return reader.GetBoolean();
+        }
+
+        throw new JsonException();
```
Comment (JerryNixon) [inline src/Config/Converters/BooleanJsonConverter.cs]:
```suggestion
        throw new JsonException("Invalid JSON value. Expected a boolean literal or a valid @expression.");
```

Comment (simonsabin) [reply src/Config/Converters/BooleanJsonConverter.cs]: This is pattern is repeated a few times in the converters.

File: CONTRIBUTING.md [hunk 8]
```diff
@@ -112,17 +112,42 @@ if [ "\$(get_files)" = '' ]; then
 fi
 
 get_files |
-    xargs dotnet format src/Azure.DataApiBuilder.Service.sln \\
-        --check \\
-        --fix-whitespace --fix-style warn --fix-analyzers warn \\
+    xargs dotnet format src/Azure.DataApiBuilder.sln \\
```
Comment (Aniruddh25) [inline CONTRIBUTING.md:115]: why are we removing `--fix-whitespace --fix-style warn --fix-analyzers warn` options? Are those not useful?

Comment (simonsabin) [reply CONTRIBUTING.md:115]: They arent valid https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-format

Not sure when they stopped being valid

File: schemas/dab.draft.schema.json [hunk 9]
```diff
@@ -1399,7 +1399,7 @@
       "oneOf":[
         {
           "type": [ "boolean", "string" ],
-          "pattern": "^(true|false|1|0|@env\\('.*'\\)|@akv\\('.*'\\))$"
+          "pattern": "^(?:true|false|1|0|@.{3}\\('.*'\\))$"
```
Comment (Aniruddh25) [inline schemas/dab.draft.schema.json]: wouldnt doing `.{3}` allow any pattern other than env or akv?

If yes, I think we should retain the previous pattern.

File: CONTRIBUTING.md (hunk 8 above)
Comment (simonsabin) [reply CONTRIBUTING.md:115]: Happy to chat over, not sure where the arguments in the hook came from

File: schemas/dab.draft.schema.json (hunk 9 above)
Comment (simonsabin) [reply schemas/dab.draft.schema.json]: This was @JerryNixon 's suggestion. Assume it was a bit of forward planning.

**Comment by simonsabin** [comment]
> Looks good, except for the pattern match for @env/@akv.

Can you discuss this with @JerryNixon and decide

**Comment by simonsabin** [comment]
Integration tests aren't passing, is that an issue?

**Comment by Aniruddh25** [comment]
> Integration tests aren't passing, is that an issue?

that's not. rerunning should fix it.

**Comment by Aniruddh25** [comment]
> > Looks good, except for the pattern match for @env/@akv.
> 
> Can you discuss this with @JerryNixon and decide

checked with Jerry. your previous pattern is what we both recommend.

File: schemas/dab.draft.schema.json (hunk 9 above)
Comment (simonsabin) [reply schemas/dab.draft.schema.json]: pushed fix

**Review by Aniruddh25 — APPROVED** [review]

File: src/Config/Converters/BooleanJsonConverter.cs [hunk 10]
```diff
@@ -0,0 +1,61 @@
...
+                _ => throw new JsonException($"Invalid boolean value. Specify either true or false."),
+            };
+            return result;
+        }
+        else
+        {
+            return reader.GetBoolean();
+        }
+
+        throw new JsonException("Invalid JSON value. Expected a boolean literal or a valid @expression.");
```
Comment (souvikghosh04) [inline src/Config/Converters/BooleanJsonConverter.cs]: the exception thrown at line 54 seems to be unreachable as all code paths return before reaching here

File: src/Config/Converters/BooleanJsonConverter.cs [hunk 11]
```diff
@@ -0,0 +1,61 @@
...
+
+            return result;
+        }
+        else if (reader.TokenType == JsonTokenType.Number)
+        {
+            bool result = reader.GetInt32() switch
+            {
+                1 => true,
+                0 => false,
+                _ => throw new JsonException($"Invalid boolean value. Specify either true or false."),
```
Comment (souvikghosh04) [inline src/Config/Converters/BooleanJsonConverter.cs]: nit: add a more specific message saying acceptable values are 1 and 0. something like - "Specify 1 for true or 0 for false"

File: src/Config/Converters/BooleanJsonConverter.cs [hunk 12]
```diff
@@ -0,0 +1,61 @@
...
+
+using System.Text.Json;
+using System.Text.Json.Serialization;
+
+namespace Azure.DataApiBuilder.Config.Converters;
+
+/// <summary>
+/// JSON converter for boolean values that also supports string representations such as
+/// "true", "false", "1", and "0". Any environment variable replacement is handled by
+/// other converters (for example, the string converter) before the value is parsed here.
```
Comment (souvikghosh04) [inline src/Config/Converters/BooleanJsonConverter.cs:12]: nit: closing `</summary>` tag missing

File: src/Config/Converters/BooleanJsonConverter.cs [hunk 13]
```diff
@@ -0,0 +1,61 @@
...
+
+            throw new JsonException("Unexpected null JSON token. Expected a boolean literal or a valid @expression.");
+        }
+
+        if (reader.TokenType == JsonTokenType.String)
+        {
+
+            string? tempBoolean = JsonSerializer.Deserialize<string>(ref reader, options);
+
+            bool result = tempBoolean?.ToLower() switch
```
Comment (souvikghosh04) [inline src/Config/Converters/BooleanJsonConverter.cs:30]: minor optimization- `ToLower()` has an allocation overhead as it creates a new string. use `StringComparison.OrdinalIgnoreCase` instead. Refer- https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1862#rule-description

File: src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs [hunk 14]
```diff
@@ -213,6 +215,138 @@ private static string GetExpectedPropertyValue(string envVarName, bool replaceEn
...
+                configJson,
+                out RuntimeConfig runtimeConfig,
+                replacementSettings: new DeserializationVariableReplacementSettings(
+                    azureKeyVaultOptions: null,
+                    doReplaceEnvVar: true,
+                    doReplaceAkvVar: false));
+
+            // Assert
+            Assert.IsTrue(IsParsed);
+            Assert.AreEqual("InstrumentationKey=test-key", runtimeConfig.Runtime.Telemetry.ApplicationInsights.ConnectionString, "Connection string should be preserved");
```
Comment (souvikghosh04) [inline src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs]: move `InstrumentationKey=test-key"` into a CONST string and use instead of repeatedly using the same hard-coded value everywhere.

Comment (simonsabin) [reply src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs]: There are a large number of strings repeated. Not sure it adds anything to make this a const.

File: src/Config/Converters/BooleanJsonConverter.cs (hunk 13 above)
Comment (simonsabin) [reply src/Config/Converters/BooleanJsonConverter.cs:30]: That doesn't work with switch. This a in frequent action that I don't think one needs to be worried about allocations.

File: src/Service.Tests/UnitTests/EnvironmentTests copy.cs [hunk 15]
```diff
@@ -0,0 +1,100 @@
+// Copyright (c) Microsoft Corporation.
```
Comment (Aniruddh25) [inline src/Service.Tests/UnitTests/EnvironmentTests copy.cs]: accidental addition of this file?

File: src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs (hunk 14 above)
Comment (souvikghosh04) [reply src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs]: that is the exact reason to move to a CONST. I see your point but to clarify the benefit:  if Application Insights 
changes their connection string format (e.g., requiring additional 
parameters), we would need to update it in 8 places.  Extracting to a const 
ensures consistency and reduces the chance of missing one during updates. 

That said, I recognize this is test code and the value is a dummy but consistency is important.

**Review by souvikghosh04 — APPROVED** [review]
Approved with suggestions.

File: src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs (hunk 14 above)
Comment (simonsabin) [reply src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs]: My point is there is no consistency. This is a test and use of a const I dont agree does anything. 
If you want to follow that you'd need to make the ALL the test configs to be based on a combination of consts.
I've followed the consistency in AddTelemetryTests.cs, EndToEndTests.cs.

File: src/Service.Tests/UnitTests/EnvironmentTests copy.cs (hunk 15 above)
Comment (simonsabin) [reply src/Service.Tests/UnitTests/EnvironmentTests copy.cs]: yep

File: src/Config/Converters/BooleanJsonConverter.cs [hunk 16]
```diff
@@ -0,0 +1,60 @@
...
+
+            return result;
+        }
+        else if (reader.TokenType == JsonTokenType.Number)
+        {
+            bool result = reader.GetInt32() switch
+            {
+                1 => true,
+                0 => false,
+                _ => throw new JsonException($"Invalid boolean value. Specify either true or false."),
```
Comment (souvikghosh04) [inline src/Config/Converters/BooleanJsonConverter.cs]: since you are checking `(reader.TokenType == JsonTokenType.Number)`, the exception message should reflect the same. update the exception message accurately and keep it consistent to the checks and error message between line 30 and line 35

Comment (simonsabin) [reply src/Config/Converters/BooleanJsonConverter.cs]: changed

File: src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs [hunk 17]
```diff
@@ -213,6 +215,138 @@ private static string GetExpectedPropertyValue(string envVarName, bool replaceEn
...
+        }
+
+        /// <summary>
+        ///  
+        /// </summary>
+        /// <param name="configValue">Value to set in the config to cause error</param>
+        /// <param name="message">Error message</param>
+        [TestMethod]
+        [DataRow("somenonboolean", "Invalid boolean value: somenonboolean. Specify either true or false.", DisplayName = "ApplicationInsights.Enabled invalid value should error")]
+        public void TestTelemetryApplicationInsightsEnabledShouldError(string configValue, string message)
```
Comment (souvikghosh04) [inline src/Service.Tests/UnitTests/RuntimeConfigLoaderJsonDeserializerTests.cs:309]: this test is failing and blocking the merge. there are other tests as well and I can't capture all of them in review comment.

```
Failed ApplicationInsights.Enabled invalid value should error [8 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<Invalid boolean value: somenonboolean. Specify either true or 1 for true, false or 0 for false>. Actual:<Invalid boolean value: somenonboolean. Specify either true or false.>. 
  Stack Trace:
     at Azure.DataApiBuilder.Service.Tests.UnitTests.RuntimeConfigLoaderJsonDeserializerTests.TestTelemetryApplicationInsightsEnabledShouldError(String configValue, String message) in D:\a\1\s\src\Service.Tests\UnitTests\RuntimeConfigLoaderJsonDeserializerTests.cs:line 347
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)

  Skipped InsertMutationForNonGraphQLTypeTable
  Skipped InsertIntoInsertableComplexView
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'Null'.
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonDocument.TryGetNamedPropertyValue(Int32 index, ReadOnlySpan`1 propertyName, JsonElement& value)
   at System.Text.Json.JsonElement.TryGetProperty(String propertyName, JsonElement& value)
   at Azure.DataApiBuilder.Service.Tests.Configuration.ConfigurationTests.ValidateMutationSucceededAtDbLayer(TestServer server, HttpClient client, String query, String queryName, String authToken, String clientRoleHeader) in D:\a\1\s\src\Service.Tests\Configuration\ConfigurationTests.cs:line 3183
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Review by souvikghosh04 — COMMENTED** [review]
some tests are failing which is blocking the merge. please ensure to run and validate the tests locally. for example- `..\CosmosTests\SchemaGeneratorTest.cs` has multiple failing tests.

**Comment by simonsabin** [comment]
Tests were failing due to inconsistencies with CR and LF endings. 
It appears that schemas are generted with CRLFs. The code formatting is enforcing LFs in git. 
This makes the results slightly undeterminstic. Had changed the gitattributes to align the .cs files with the code formatting rules, but that breaks as files checked out get LF line endings which breaks the test.

**Comment by simonsabin** [comment]
Are these test failues transient?
