### PR TITLE
Change autoentities `patterns.name` default value

### LINKED ISSUE #3455: [Bug]: autoentities does not honor schema
## What happened?
I had two tables names `magazines` in 2 different schemas: 
`foo.magazines` and `bar.magazines`

Configuration used:

 ```
 "entities": {},
  "autoentities": {
    "default": {
      "template": {
        "mcp": { "dml-tools": true },
        "rest": { "enabled": true },
        "graphql": { "enabled": true },
        "health": { "enabled": true },
        "cache": {
          "enabled": false
        }
      },
      "permissions": [
        {
          "role": "anonymous",
          "actions": [
            "create", "read", "update", "delete"
          ]
        }
      ]
    }
  }
```

dab could not start.

Saw this error in relevant output.

When I deleted one of the magazines tables, dab started. This means the autoentities feature does not honor schema when comparing entity names.

### Version

2.0.0-rc

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

_No response_

### Relevant log output

```
fail: Azure.DataApiBuilder.Service.Startup[0]
      Unable to complete runtime initialization. Refer to exception for error details.
      **Azure.DataApiBuilder.Service.Exceptions.DataApiBuilderException: Entity with name 'magazines' already exists. Cannot create new entity from autoentity pattern with definition-name 'default'.**
         at Azure.DataApiBuilder.Core.Services.MsSqlMetadataProvider.GenerateAutoentitiesIntoEntities(IReadOnlyDictionary`2 autoentities) in /_/src/Core/Services/MetadataProviders/MsSqlMetadataProvider.cs:line 358
         at Azure.DataApiBuilder.Core.Services.SqlMetadataProvider`3.InitializeAsync() in /_/src/Core/Services/MetadataProviders/SqlMetadataProvider.cs:line 336
         at Azure.DataApiBuilder.Core.Services.MetadataProviders.MetadataProviderFactory.InitializeAsync() in /_/src/Core/Services/MetadataProviders/MetadataProviderFactory.cs:line 95
         at Azure.DataApiBuilder.Service.Startup.PerformOnConfigChangeAsync(IApplicationBuilder app) in /_/src/Service/Startup.cs:line 1209
fail: Azure.DataApiBuilder.Service.Startup[0]
      Could not initialize the engine with the runtime config file: dab-config.json
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by RubenCerna2079**
## Why make this change?
- Fixes issue #3455 

## What is this change?
This changes the default value of the `patterns.name` property inside `autoentities` so that it uses both the {schema} and {object} in order to allow users to use multiple objects that have the same name but are from different schemas without the need to do additional changes to the config file.

This PR is dependent on PR #3468.

## How was this tested?

- [X] Integration Tests
- [ ] Unit Tests
- [X] Manual Tests
Used sample below to ensure that different entities with the same object name but different schema name can be created without the need to change the `patterns.name` property.

## Sample Request(s)
```
"AllMagazineObjects": {
  "patterns": {
    "include": [
      "%.magazines"
    ]
  },
  "permissions": [
    {
      "role": "anonymous",
      "actions": [
        {
          "action": "*"
        }
      ]
    }
  ]
}
```
image
image

### CODE REVIEW

File: src/Config/ObjectModel/AutoentityPatterns.cs [hunk 1]
```diff
@@ -51,7 +51,7 @@ public AutoentityPatterns(
         }
         else
         {
-            this.Name = "{object}";
+            this.Name = "{schema}_{object}";
```
[the remark this answers is not in the document]
Comment (RubenCerna2079) [reply src/Config/ObjectModel/AutoentityPatterns.cs:54]: This is something that was expected, unsure of which tests might fail. So I will be addressing those after the pipeline runs

**Review by Aniruddh25 — APPROVED** [review]

File: src/Config/ObjectModel/AutoentityPatterns.cs (hunk 1 above)
Comment (Aniruddh25) [inline src/Config/ObjectModel/AutoentityPatterns.cs:54]: Does this PR also fix the other issue where at the time discovery of metadata for autoentities, dbo is assumed to be the default schema to look for the underlying table? I had opened a different issue for that.

**Review by Aniruddh25 — CHANGES_REQUESTED** [review]
Dependent on PR #3468

File: src/Config/ObjectModel/AutoentityPatterns.cs (hunk 1 above)
Comment (RubenCerna2079) [reply src/Config/ObjectModel/AutoentityPatterns.cs:54]: No, that is done specifically on PR #3468.
I added it to the PR description.

File: schemas/dab.draft.schema.json [hunk 2]
```diff
@@ -845,8 +845,8 @@
                 },
                 "name": {
                   "type": "string",
-                  "description": "Entity name interpolation pattern using {schema} and {object}. Null defaults to {object}. Must be unique for every entity inside the pattern",
-                  "default": "{object}"
+                  "description": "Entity name interpolation pattern using {schema} and {object}. Null defaults to {schema}_{object}. Must be unique for every entity inside the pattern",
+                  "default": "{schema}_{object}"
```
Comment (souvikghosh04) [inline schemas/dab.draft.schema.json:851]: do we have a task to update the document (by Jerry) this since the default entity names will now have schema?

**Review by souvikghosh04 — APPROVED** [review]
We need to document the new default behavior

File: schemas/dab.draft.schema.json (hunk 2 above)
Comment (RubenCerna2079) [reply schemas/dab.draft.schema.json:851]: I already updated all the internal documents. If you mean that we need to add a task for updating the documentation, then that still has to be done.

Comment (RubenCerna2079) [reply schemas/dab.draft.schema.json:851]: Just created the task https://github.com/Azure/data-api-builder/issues/3483

**Review by Aniruddh25 — APPROVED** [review]
Test still seem to fail, please run all tests locally to ensure they pass instead of relying on pipeline since the latter could be time consuming

File: src/Service.Tests/Configuration/ConfigurationTests.cs [hunk 3]
```diff
@@ -5651,7 +5651,7 @@ public async Task TestAutoentitiesWithSameObjectDifferentSchemas()
                     "PublisherAutoEntity", new Autoentity(
                         Patterns: new AutoentityPatterns(
                             Include: null,
-                            Exclude: null,
+                            Exclude: new[] { "dbo.GQLmappings", "dbo.graphql_incompatible", "dbo.brokers" },
```
Comment (Aniruddh25) [inline src/Service.Tests/Configuration/ConfigurationTests.cs:5654]: how did you figure out these should be excluded? 
I had to do this in my testing.
Can you please add the entityName to this exception in SqlMetadataProvider:

                    throw new DataApiBuilderException(
                       message: $"The column '{columnName}' from {entityName} violates GraphQL name restrictions.",
                       statusCode: HttpStatusCode.ServiceUnavailable,
                       subStatusCode: DataApiBuilderException.SubStatusCodes.ErrorInInitialization);

Comment (Aniruddh25) [reply src/Service.Tests/Configuration/ConfigurationTests.cs:5654]: nvm, you can do it in a different PR too since all tests pass here,

**Review by Aniruddh25 — APPROVED** [review]

File: src/Service.Tests/Configuration/ConfigurationTests.cs (hunk 3 above)
Comment (RubenCerna2079) [reply src/Service.Tests/Configuration/ConfigurationTests.cs:5654]: I created a new issue to track this https://github.com/Azure/data-api-builder/issues/3486
