### PR TITLE
[Health]: Test Case for Rest and GraphQL Requests to DAB during health check

### LINKED ISSUE #2662: [HealthEndpoint] Test cases for GraphQL and REST in Health Check Report
The testing for Health Endpoint is failing for GraphQL and Rest calls with the error `One or more errors occurred. (No connection could be made because the target machine actively refused it. (localhost:5000)`. This is due to an in memory server running and not an http server for internal calls to work on http://localhost endpoint. 
We need to modify the HttpUtilities to pass the HttpClient from the Startup.cs and use the client from the factory instead of creating new. 

But if /health internally calls /api and /graphql, and you're using the same in-memory TestServer, you might hit issues like:

- Loopbacks not working: Since the same server is handling the request and the internal call, it could cause reentrancy issues or socket errors.
- Your test app is running in-memory (via TestServer or WebApplicationFactory), and not actually listening on a real network port.

Boot up your app in-memory for integration tests.
Run your app in-memory via test code, likely using WebApplicationFactory, TestServer, or similar.
That means: Your app should be bound to an external port like [http://localhost:80](http://localhost/)
Instead of in-memory (via the HttpClient returned from factory.CreateClient())
You need to inject the HttpClient from the test context into your health check logic, so it uses the in-memory test server instead of trying to call a real external address.

### PR DESCRIPTION
**Pull request by sezal98**
## Why make this change?
Resolves #2662 

## What is this change?
1. Created the HttpUtilities with HttpClient already instantiated and basic details filled from Startup.cs
2. Using this httpClient, call the REST and GraphQL requests with relative URI 
3. Created a function in DatabaseObject to access mapping dict as it is an abstract class which was not allowed to be mocked. 
4. Test cases for both REST and GraphQL
5. Rest Test case: Mock the client to return a 200 response when we receive a GET request with specific URI. Validate the error message from HttpUtilities should be null.
6. GraphQL Test case: Mock the client to return a 200 response when we get a POST request with /graphql URI and content payload. Mock the Dabase Object with columns in the entity map to only return the db object when a certain entity is called for. 

## How was this tested?

- [ ] Integration Tests
- [x] Unit Tests

## Sample Request(s)
Requests are running as expected. Test cases added for Rest and Graphql

### CODE REVIEW

File: src/Service/HealthCheck/HttpUtilities.cs [hunk 1]
```diff
@@ -166,36 +139,33 @@ public void ConfigureApiRoute(HttpContext httpContext)
                 // In case any primitive column names are present, execute the query
                 if (columnNames.Any())
                 {
-                    using (HttpClient client = CreateClient(apiRoute))
+                    string jsonPayload = Utilities.CreateHttpGraphQLQuery(graphqlObjectName, columnNames, entity.EntityFirst);
+                    HttpContent content = new StringContent(jsonPayload, Encoding.UTF8, Utilities.JSON_CONTENT_TYPE);
+
+                    HttpRequestMessage message = new(method: HttpMethod.Post, requestUri: graphqlUriSuffix)
```
[the remark this answers is not in the document]
Comment (sezal98) [reply src/Service/HealthCheck/HttpUtilities.cs:145]: We want to create a relative URIs since base address is already set in the startup.cs

File: src/Service/HealthCheck/HttpUtilities.cs [hunk 2]
```diff
@@ -208,23 +178,6 @@ public void ConfigureApiRoute(HttpContext httpContext)
...
-                DefaultRequestHeaders =
-                {
-                    Accept = { new MediaTypeWithQualityHeaderValue(Utilities.JSON_CONTENT_TYPE) }
-                },
-                Timeout = TimeSpan.FromSeconds(200),
-            };
-        }
-
         // Updates the entity key name to camel case for the health check report.
         public static string LowerFirstLetter(string input)
```
[the remark this answers is not in the document]
Comment (sezal98) [reply src/Service/HealthCheck/HttpUtilities.cs:182]: `string graphqlObjectName = LowerFirstLetter(entity.GraphQL.Plural.Pascalize());` I did account for two words like Lastname which gets changed to `lastnames`. The function will also generate this which is what is required in GraphQL
image
However since we already have this function, modified to use this.

File: src/Service.Tests/Configuration/ConfigurationTests.cs [hunk 3]
```diff
@@ -4667,22 +4454,20 @@ public async Task TestNoDepthLimitOnGrahQLInNonHostedMode(int? depthLimit)
         /// </summary>
         /// <param name="entityMap">Collection of entityName -> Entity object.</param>
         /// <param name="enableGlobalRest">flag to enable or disabled REST globally.</param>
-        private static void CreateCustomConfigFile(Dictionary<string, Entity> entityMap, bool enableGlobalRest = true, bool enableGlobalGraphql = true, bool enableGlobalHealth = true, bool enableDatasourceHealth = true, HostMode hostMode = HostMode.Production)
+        private static void CreateCustomConfigFile(Dictionary<string, Entity> entityMap, bool enableGlobalRest = true)
```
Comment (Aniruddh25) [inline src/Service.Tests/Configuration/ConfigurationTests.cs:4457]: Is `enableGlobalGraphQL` not used by any of the existing tests?

File: src/Service/Startup.cs [hunk 4]
```diff
@@ -270,6 +271,27 @@ public void ConfigureServices(IServiceCollection services)
             //Enable accessing HttpContext in RestService to get ClaimsPrincipal.
             services.AddHttpContextAccessor();
 
+            services.AddHttpClient("ContextConfiguredHealthCheckClient")
+                .ConfigureHttpClient((serviceProvider, client) =>
+                {
```
Comment (Aniruddh25) [inline src/Service/Startup.cs:276]: does adding HttpClient to the service provider help with testing?

File: src/Service.Tests/Configuration/HealthEndpointTests.cs [hunk 5]
```diff
@@ -0,0 +1,437 @@
...
+            // Act
+            string errorMessageFromGraphQL = httpUtilities.ExecuteGraphQLQuery(
+                graphqlUriSuffix: "/graphql",
+                entityName: runtimeConfig.Entities.First().Key,
+                entity: runtimeConfig.Entities.First().Value,
+                incomingRoleHeader: string.Empty,
+                incomingRoleToken: string.Empty);
+
+            // Assert
+            Assert.IsNull(errorMessageFromGraphQL);
```
Comment (Aniruddh25) [inline src/Service.Tests/Configuration/HealthEndpointTests.cs:233]: We should have a test for the failure case as well. Mock a failed response, and verify the httputilities returns the error

File: src/Service.Tests/Configuration/ConfigurationTests.cs [hunk 6]
```diff
@@ -4017,219 +4016,7 @@ public async Task HealthEndpoint_ValidateContents()
...
-                Assert.AreEqual(
-                    expected: ProductInfo.GetDataApiBuilderUserAgent(),
-                    actual: appNameValue.ToString(),
-                    message: "Unexpected or missing DAB user agent string.");
-            }
-            else
-            {
-                Assert.Fail();
-            }
+            HealthEndpointTests.ValidateBasicDetailsHealthCheckResponse(responseProperties);
```
[the remark this answers is not in the document]
Comment (sezal98) [reply src/Service.Tests/Configuration/ConfigurationTests.cs:4019]: I dont see any missing tab in this line. Doesnt show up in formatting as well.

File: src/Service.Tests/Configuration/ConfigurationTests.cs (hunk 3 above)
Comment (sezal98) [reply src/Service.Tests/Configuration/ConfigurationTests.cs:4457]: GraphQL was always enabled by default. Rest was switched on and off in multiple tests.

File: src/Service/Startup.cs (hunk 4 above)
Comment (sezal98) [reply src/Service/Startup.cs:276]: yes we can create a mock httpclient now and pass it to the Httputilities. Before this I was creating httpclient internally in this file and hence mocking was not possible.

File: src/Service.Tests/Configuration/HealthEndpointTests.cs [hunk 7]
```diff
@@ -0,0 +1,437 @@
...
+            HttpUtilities httpUtilities = new(
+                logger.Object,
+                metadataProviderFactory.Object,
+                provider,
+                mockHttpClientFactory.Object);
+
+            // Act
+            string errorMessageFromGraphQL = httpUtilities.ExecuteGraphQLQuery(
+                graphqlUriSuffix: "/graphql",
+                entityName: runtimeConfig.Entities.First().Key,
```
[the remark this answers is not in the document]
Comment (sezal98) [reply src/Service.Tests/Configuration/HealthEndpointTests.cs:227]: yes it would have

File: src/Service.Tests/Configuration/HealthEndpointTests.cs (hunk 5 above)
Comment (sezal98) [reply src/Service.Tests/Configuration/HealthEndpointTests.cs]: Added negative test cases

**Review by Aniruddh25 — APPROVED** [review]
LGTM, thanks for adding these tests!

File: src/Service/HealthCheck/HealthCheckHelper.cs [hunk 8]
```diff
@@ -249,7 +248,7 @@ private void PopulateEntityHealth(ComprehensiveHealthCheckReport ComprehensiveHe
                 {
                     ComprehensiveHealthCheckReport.Checks ??= new List<HealthCheckResultEntry>();
 
-                    (int, string?) response = ExecuteGraphQLEntityQuery(runtimeConfig.GraphQLPath, entityValue, entityKeyName);
+                    (int, string?) response = await ExecuteGraphQLEntityQueryAsync(runtimeConfig.GraphQLPath, entityValue, entityKeyName);
```
Comment (RubenCerna2079) [inline src/Service/HealthCheck/HealthCheckHelper.cs:251]: Why only change the name for this one by adding `Async` and not the rest of the functions?

File: src/Service/HealthCheck/HttpUtilities.cs [hunk 9]
```diff
@@ -88,50 +74,44 @@ public void ConfigureApiRoute(HttpContext httpContext)
...
-                string apiRoute = Utilities.GetServiceRoute(_apiRoute, restUriSuffix);
+                string apiRoute = $"{restUriSuffix}{Utilities.CreateHttpRestQuery(entityName, first)}";
                 if (string.IsNullOrEmpty(apiRoute))
                 {
                     LogTrace("The API route is not available, hence HealthEndpoint is not available.");
                     return errorMessage;
                 }
 
-                if (!Program.CheckSanityOfUrl(apiRoute))
+                if (!Program.CheckSanityOfUrl($"{_httpClient.BaseAddress}{restUriSuffix}"))
```
Comment (RubenCerna2079) [inline src/Service/HealthCheck/HttpUtilities.cs:90]: Why was the variable `apiRoute` changed?

File: src/Service/HealthCheck/HttpUtilities.cs [hunk 10]
```diff
@@ -145,18 +125,11 @@ public void ConfigureApiRoute(HttpContext httpContext)
 
         // Executes the GraphQL query by sending a POST request to the API.
         // Internally calls the metadata provider to fetch the column names to create the graphql payload.
-        public string? ExecuteGraphQLQuery(string graphqlUriSuffix, string entityName, Entity entity, string incomingRoleHeader, string incomingRoleToken)
+        public async Task<string?> ExecuteGraphQLQuery(string graphqlUriSuffix, string entityName, Entity entity, string incomingRoleHeader, string incomingRoleToken)
         {
             string? errorMessage = null;
-            // Base URL of the API that handles SQL operations
-            string apiRoute = Utilities.GetServiceRoute(_apiRoute, graphqlUriSuffix);
-            if (string.IsNullOrEmpty(apiRoute))
```
Comment (RubenCerna2079) [inline src/Service/HealthCheck/HttpUtilities.cs:153]: Why was this check removed while in the RestQuery it is still there?

File: src/Service/Startup.cs [hunk 11]
```diff
@@ -270,6 +271,27 @@ public void ConfigureServices(IServiceCollection services)
...
+                        string baseUri = $"{httpContext.Request.Scheme}://{httpContext.Request.Host}";
+                        client.BaseAddress = new Uri(baseUri);
+
+                        // Set default Accept header
+                        client.DefaultRequestHeaders.Accept.Clear();
+                        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
+                    }
+
+                    // Optional: Set a timeout
+                    client.Timeout = TimeSpan.FromSeconds(200);
```
Comment (RubenCerna2079) [inline src/Service/Startup.cs:292]: How is this optional and why would we want it optional?

File: src/Service.Tests/Configuration/HealthEndpointTests.cs [hunk 12]
```diff
@@ -0,0 +1,492 @@
...
+                    if (enableEntityHealth)
+                    {
+                        ValidateEntityRestAndGraphQLResponse(responseProperties, enableEntityRest, enableEntityGraphQL, enableGlobalRest, enableGlobalGraphql);
+                    }
+                }
+            }
+        }
+
+        [TestMethod]
+        public async Task TestHealthCheckRestResponseAsync()
```
Comment (RubenCerna2079) [inline src/Service.Tests/Configuration/HealthEndpointTests.cs:105]: I think you should add a comment explaining what this test does

File: src/Service.Tests/Configuration/HealthEndpointTests.cs [hunk 13]
```diff
@@ -0,0 +1,492 @@
...
+                incomingRoleToken: string.Empty
+            );
+
+            // Assert
+            // Validate the null response from the REST API call 
+            Assert.IsNull(errorMessageFromRest);
+        }
+
+        [TestMethod]
+        public async Task TestFailureHealthCheckRestResponseAsync()
```
Comment (RubenCerna2079) [inline src/Service.Tests/Configuration/HealthEndpointTests.cs:129]: I think there should also be a comment here

File: src/Service.Tests/Configuration/HealthEndpointTests.cs [hunk 14]
```diff
@@ -0,0 +1,492 @@
...
+                incomingRoleHeader: string.Empty,
+                incomingRoleToken: string.Empty
+            );
+
+            // Assert
+            Assert.IsNotNull(errorMessageFromRest);
+        }
+
+        [TestMethod]
+        public async Task TestHealthCheckGraphQLResponseAsync()
```
Comment (RubenCerna2079) [inline src/Service.Tests/Configuration/HealthEndpointTests.cs:152]: At the very least the test methods should have a comment summarizing what they do.

File: src/Service.Tests/Configuration/HealthEndpointTests.cs [hunk 15]
```diff
@@ -0,0 +1,492 @@
...
+                entityName: runtimeConfig.Entities.First().Key,
+                entity: runtimeConfig.Entities.First().Value,
+                incomingRoleHeader: string.Empty,
+                incomingRoleToken: string.Empty);
+
+            // Assert
+            Assert.IsNotNull(errorMessageFromGraphQL);
+        }
+
+        private static HttpUtilities SetupRestTest(RuntimeConfig runtimeConfig, HttpStatusCode httpStatusCode = HttpStatusCode.OK)
```
Comment (RubenCerna2079) [inline src/Service.Tests/Configuration/HealthEndpointTests.cs:189]: I think it would be a good idea to create a region for the helper methods, so it is easier to identify them

File: src/Service/HealthCheck/HttpUtilities.cs (hunk 9 above)
Comment (sezal98) [reply src/Service/HealthCheck/HttpUtilities.cs:90]: Not needed anymore

File: src/Service/HealthCheck/HttpUtilities.cs (hunk 10 above)
Comment (sezal98) [reply src/Service/HealthCheck/HttpUtilities.cs:153]: In rest we create the entire query in the URI itself. However, in GraphQL we take the basic query of /graphql and add parameters in payload. 
`CheckSanityOfUrl` already validates the URi of null or empty so we dont need to do again.

File: src/Service/Startup.cs (hunk 11 above)
Comment (sezal98) [reply src/Service/Startup.cs:292]: If you don’t set client.Timeout manually, the HttpClient will use the default timeout, which is:
`TimeSpan.FromSeconds(100)`
This means every HTTP request made by this client will wait a maximum of 100 seconds for a response before throwing a TaskCanceledException. Hence, I am setting 200 here. We can change if we want.

**Review by Aniruddh25 — APPROVED** [review]

**Review by RubenCerna2079 — APPROVED** [review]
LGTM
