### PR TITLE
fix dataSourceName not found exception in `dab validate`

### LINKED ISSUE #2039: [Bug]: `dab validate` getting exception due to datasourceName mismatch
### What happened?

image

### Version

0.11.6-rc

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by abhishekkumams**
## Why make this change?

-  Closes #2039 
- `dab validate` was throwing exception stating `dataSourcename is not found`. This PR aims to fix it.

## What is this change?
- RuntimeConfig object stores dataSourceName information.
- previously the RuntimeConfig object was created in CLI during deserialization and sent to Engine Code. And In engine code when we setup metadatprovider we again create the dataSourceName info, due to which there is a mismatch.
- So, we are not sending the RuntimeConfig object from CLI, and in Engine we are sourcing it directly from RuntimeConfigProvider. (similar to how it's done while starting the engine).
- Therefore, Doing the deserialization only in a single place in the engine itself, improving performance as well.

# Before
image

## After
image

### CODE REVIEW

File: src/Core/Configurations/RuntimeConfigValidator.cs [hunk 1]
```diff
@@ -150,10 +150,20 @@ public void ValidateAppInsightsTelemetryConnectionString(RuntimeConfig runtimeCo
     /// <returns>true if no validation failures, else false.</returns>
     public async Task<bool> TryValidateConfig(
         string configFilePath,
-        RuntimeConfig runtimeConfig,
```
Comment (seantleonard) [inline src/Core/Configurations/RuntimeConfigValidator.cs:153]: need to update method summary with removed param

File: src/Core/Configurations/RuntimeConfigValidator.cs [hunk 2]
```diff
@@ -150,10 +150,20 @@ public void ValidateAppInsightsTelemetryConnectionString(RuntimeConfig runtimeCo
...
         ILoggerFactory loggerFactory,
         bool isValidateOnly = false)
     {
+        RuntimeConfig runtimeConfig;
+        try
+        {
+            runtimeConfig = _runtimeConfigProvider.GetConfig();
```
Comment (seantleonard) [inline src/Core/Configurations/RuntimeConfigValidator.cs:159]: `_runtimeConfigProvider.GetConfig()` parses the config and doesn't just returned an already processed runtimeconfig object?

File: src/Cli.Tests/ValidateConfigTests.cs [hunk 3]
```diff
@@ -60,4 +60,20 @@ public void TestConfigWithInvalidConfigProperties()
         bool isConfigValid = ConfigGenerator.IsConfigValid(validateOptions, _runtimeConfigLoader!, _fileSystem!);
         Assert.IsFalse(isConfigValid);
     }
+
+    /// <summary>
+    /// This method validates that the IsConfigValid method returns false when the config is empty.
+    /// This is to test no exception gets thrown with validate during failure config deserialization.
```
Comment (seantleonard) [inline src/Cli.Tests/ValidateConfigTests.cs:66]: how are you testing that no exception is thrown? By ensuring `ConfigGenerator.IsConfigValid(...)` only returns a bool?

File: src/Cli/ConfigGenerator.cs [hunk 4]
```diff
@@ -1091,24 +1091,14 @@ public static bool IsConfigValid(ValidateOptions options, FileSystemRuntimeConfi
...
-            }
+            _logger.LogInformation("Validating config file: {runtimeConfigFile}", runtimeConfigFile);
 
             RuntimeConfigProvider runtimeConfigProvider = new(loader);
 
             ILogger<RuntimeConfigValidator> runtimeConfigValidatorLogger = LoggerFactoryForCli.CreateLogger<RuntimeConfigValidator>();
             RuntimeConfigValidator runtimeConfigValidator = new(runtimeConfigProvider, fileSystem, runtimeConfigValidatorLogger, true);
 
-            return runtimeConfigValidator.TryValidateConfig(runtimeConfigFile, deserializedRuntimeConfig, LoggerFactoryForCli).Result;
+            return runtimeConfigValidator.TryValidateConfig(runtimeConfigFile, LoggerFactoryForCli).Result;
```
Comment (seantleonard) [inline src/Cli/ConfigGenerator.cs:1101]: In your PR desription:
> So, we are not sending the RuntimeConfig object from CLI, and in Engine we are sourcing it directly from RuntimeConfigProvider. (similar to how it's done while starting the engine).
Therefore, Doing the deserialization only in a single place in the engine itself, improving performance as well.

Those two changes in behavior hold true because `runtimeConfigValidator.TryValidateConfig(runtimeConfigFile, LoggerFactoryForCli).Result;` is "engine code" and CLI no longer passes its own `deserializedRuntimeConfig` object?  just confirming my understanding.

File: src/Cli.Tests/ValidateConfigTests.cs (hunk 3 above)
Comment (seantleonard) [reply src/Cli.Tests/ValidateConfigTests.cs:66]: in `IsConfigValid` there is a call to `runtimeConfigValidator.TryValidateConfig(...)` which calls `ValidateEntitiesMetadata()`. Could  `ValidateEntitiesMetadata()` throw an exception which resuls in a bool not being returned for `IsConfigValid`? I suppose this PR's change only affects the mismatched dataSourceName, but unclear if it prevents other exceptions from being printed to the console

File: src/Cli/ConfigGenerator.cs (hunk 4 above)
Comment (abhishekkumams) [reply src/Cli/ConfigGenerator.cs:1101]: correct.

File: src/Cli.Tests/ValidateConfigTests.cs (hunk 3 above)
Comment (abhishekkumams) [reply src/Cli.Tests/ValidateConfigTests.cs:66]: correct, this PR is just to fix the issue of dataSourceName not found. 
Since, I moved the deserialization logic to a single place, I added this test to make sure exceptions due to deserialization failures are captured correctly.

File: src/Core/Configurations/RuntimeConfigValidator.cs (hunk 2 above)
Comment (abhishekkumams) [reply src/Core/Configurations/RuntimeConfigValidator.cs:159]: it does if same instance is used. First, CLI was trying to deserialize the config which creates the dataSourceName. Now, In the engine during validation, when we create a new instance for MetadataProviderFactory, it also creates a mapping between DataSourceName and metadataProvider. This dataSourceName differs from the one created in CLI. According to our code structure `MetadataProviderFactory` should be setup first and then used to get the config which keeps thing in sync.

For your question, yes it won't parse the config again, but the mapping that exists in metadataProviderFactory will differ, if we don't first setup metadataProvider and then source config.
image

File: src/Core/Configurations/RuntimeConfigValidator.cs [hunk 5]
```diff
@@ -144,16 +144,25 @@ public void ValidateAppInsightsTelemetryConnectionString(RuntimeConfig runtimeCo
...
+        }
```
Comment (Aniruddh25) [inline src/Core/Configurations/RuntimeConfigValidator.cs:159]: Shouldn't we be using _runtimeConfigProvier.TryGetConfig?

File: src/Cli.Tests/ValidateConfigTests.cs [hunk 6]
```diff
@@ -60,4 +60,20 @@ public void TestConfigWithInvalidConfigProperties()
...
+    /// </summary>
+    [TestMethod]
+    public void TestValidateWithEmptyConfig()
```
Comment (Aniruddh25) [inline src/Cli.Tests/ValidateConfigTests.cs:69]: Shouldn't we add another test case which would have failed with the datasourceName not found exception without your fix?

**Review by Aniruddh25 — CHANGES_REQUESTED** [review]
Needs the right testing

File: src/Cli.Tests/ValidateConfigTests.cs (hunk 6 above)
Comment (abhishekkumams) [reply src/Cli.Tests/ValidateConfigTests.cs:69]: added a test which test the whole deserilization to validation.

File: src/Service.Tests/Configuration/ConfigurationTests.cs [hunk 7]
```diff
@@ -1062,6 +1062,45 @@ public void TestConfigPropertiesAreValid()
             configValidator.ValidateConfigProperties();
         }
 
+        /// <summary>
+        /// This method tests that config file is validated correctly and no exceptions are thrown.
+        /// </summary>
+        [TestMethod("Validates the complete config."), TestCategory(TestCategory.MSSQL)]
+        public async Task TestConfigIsValid()
```
Comment (Aniruddh25) [inline src/Service.Tests/Configuration/ConfigurationTests.cs:1069]: Why is this not added to `ConfigValidationUnitTests.cs`?

**Review by Aniruddh25 — APPROVED** [review]

File: src/Service.Tests/Configuration/ConfigurationTests.cs (hunk 7 above)
Comment (abhishekkumams) [reply src/Service.Tests/Configuration/ConfigurationTests.cs:1069]: this is an integration test and all the integration tests related to validations are in this class.

File: src/Cli.Tests/ValidateConfigTests.cs (hunk 3 above)
Comment (severussundar) [inline src/Cli.Tests/ValidateConfigTests.cs:66]:
```suggestion
    /// This is to validate that no exceptions are thrown with validate for failures during config deserialization.
```

File: src/Cli.Tests/ValidateConfigTests.cs [hunk 8]
```diff
@@ -60,4 +60,20 @@ public void TestConfigWithInvalidConfigProperties()
...
+    {
+        // create an empty config file
+        ((MockFileSystem)_fileSystem!).AddFile(TEST_RUNTIME_CONFIG_FILE, string.Empty);
+
+        ValidateOptions validateOptions = new(TEST_RUNTIME_CONFIG_FILE);
+
+        bool isConfigValid = ConfigGenerator.IsConfigValid(validateOptions, _runtimeConfigLoader!, _fileSystem!);
```
Comment (severussundar) [inline src/Cli.Tests/ValidateConfigTests.cs:76]: Maybe enclose this statement within a try-catch block to handle any exceptions (if they get thrown) and fail the test within the catch block?

File: src/Service.Tests/Configuration/ConfigurationTests.cs [hunk 9]
```diff
@@ -1062,6 +1062,45 @@ public void TestConfigPropertiesAreValid()
...
+        {
+            TestHelper.SetupDatabaseEnvironment(MSSQL_ENVIRONMENT);
+            DataSource dataSource = new(DatabaseType.MSSQL,
```
Comment (severussundar) [inline src/Service.Tests/Configuration/ConfigurationTests.cs:1072]: Could we include a test case where the dataSource is invalid in the integration test as well

Comment (abhishekkumams) [reply src/Service.Tests/Configuration/ConfigurationTests.cs]: those tests already exists

File: src/Cli.Tests/ValidateConfigTests.cs (hunk 8 above)
Comment (abhishekkumams) [reply src/Cli.Tests/ValidateConfigTests.cs]: updated

File: src/Service.Tests/Configuration/ConfigurationTests.cs (hunk 9 above)
Comment (abhishekkumams) [reply src/Service.Tests/Configuration/ConfigurationTests.cs]: i've also updated the test to use the main integration test config
