### PR TITLE
Modified capitalization in metadata queries (#1896)

### LINKED ISSUE #1896: [Bug]: Builder Not Working For MSSQL Databases With Case Sensitive Collation (Azure.DataApiBuilder.Core.Resolvers.QueryExecutor)
### What happened?

A bug happened!

When starting the data API builder, it goes out to a couple system tables (sys.columns and information_schema.columns) to check for read-only fields. The following syntax is employed by the app:
```
SELECT ifsc.column_name
from sys.columns as sc
INNER JOIN information_schema.columns as ifsc ON ( sc.is_computed = 1 or ifsc.data_type = 'timestamp' )
						AND sc.object_id = object_id(@param1+'.'+@param2)
						and ifsc.table_name = @param1
						AND ifsc.table_schema = @param2
						and ifsc.column_name = sc.name;
```
This works fine for the out-of-the-box database collation. But when the database is set to a case sensitive collation, the query fails with 'invalid object' error. Below is the same query, with the correct case for the field names, so it should work with both case-sensitive and case-insensitive collations:
```
SELECT ifsc.COLUMN_NAME
from sys.columns as sc
INNER JOIN INFORMATION_SCHEMA.COLUMNS as ifsc ON ( sc.is_computed = 1 or ifsc.DATA_TYPE = 'timestamp' )
						AND sc.object_id = object_id(@param1+'.'+@param2)
						AND ifsc.TABLE_NAME = @param1
						AND ifsc.TABLE_SCHEMA = @param2
						AND ifsc.COLUMN_NAME = sc.name;
```

Wanted to create a bug report before attempting to create branches myself. I suspect that MSSQL queries further in the app may have a similar issue since there's no test for this.

### Version

0.9.7+e560142426d1c080b9fd7b7fabff51a276f6bf61

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

REST

### Relevant log output

```Text
dab start --config "C:\Users\sample_user\dab-config.json"

Information: Microsoft.DataApiBuilder 0.9.7+e560142426d1c080b9fd7b7fabff51a276f6bf61
Information: Generating default config file: C:\Users\sample_user\dab-config.json
Information: Config file generated.
Information: SUGGESTION: Use 'dab add [entity-name] [options]' to add new entities in your config.
Information: Microsoft.DataApiBuilder 0.9.7+e560142426d1c080b9fd7b7fabff51a276f6bf61
Information: User provided config file: C:\Users\sample_user\dab-config.json
Loading config file from C:\Users\sample_user\dab-config.json.
Information: Added new entity: DUAL with source: dbo.DUAL and permissions: anonymous:*.
Information: SUGGESTION: Use 'dab update [entity-name] [options]' to update any entities in your config.
Information: Microsoft.DataApiBuilder 0.9.7+e560142426d1c080b9fd7b7fabff51a276f6bf61
Information: User provided config file: C:\Users\sample_user\dab-config.json
Loading config file from C:\Users\sample_user\dab-config.json.
Information: Loaded config file: C:\Users\sample_user\dab-config.json
Information: Setting default minimum LogLevel: Debug for Development mode.
Starting the runtime engine...
Loading config file from C:\Users\sample_user\dab-config.json.
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[63]
      User profile is available. Using 'C:\Users\sample_user\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Azure.DataApiBuilder.Core.Services.ISqlMetadataProvider[0]
      [DUAL] REST path: /api/DUAL
dbug: Azure.DataApiBuilder.Core.Resolvers.IQueryExecutor[0]
       Executing query: SELECT STE.type_desc FROM sys.triggers ST inner join sys.trigger_events STE On ST.object_id = STE.object_id AND ST.parent_id = object_id(@param0 + '.' + @param1) WHERE ST.is_disable
d = 0;
dbug: Azure.DataApiBuilder.Core.Resolvers.IQueryExecutor[0]
       Executing query: SELECT ifsc.column_name from sys.columns as sc INNER JOIN information_schema.columns as ifsc ON (sc.is_computed = 1 or ifsc.data_type = 'timestamp') AND sc.object_id = object_id(@pa
ram0+'.'+@param1) and ifsc.table_name = @param1 AND ifsc.table_schema = @param0 and ifsc.column_name = sc.name;
fail: Azure.DataApiBuilder.Core.Resolvers.IQueryExecutor[0]
       Query execution error due to:
Invalid object name 'information_schema.columns'.
      Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'information_schema.columns'.
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__209_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Azure.DataApiBuilder.Core.Resolvers.QueryExecutor`1.ExecuteQueryAgainstDbAsync[TResult](TConnection conn, String sqltext, IDictionary`2 parameters, Func`3 dataReaderHandler, HttpContext httpCon
text, List`1 args)
      ClientConnectionId:3f9f4563-3a15-449a-a262-0a8838217224
      Error Number:208,State:1,Class:16
fail: Azure.DataApiBuilder.Service.Startup[0]
      Unable to complete runtime initialization. Refer to exception for error details.
      Azure.DataApiBuilder.Service.Exceptions.DataApiBuilderException: Invalid object name 'information_schema.columns'.
       ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'information_schema.columns'.
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__209_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Azure.DataApiBuilder.Core.Resolvers.QueryExecutor`1.ExecuteQueryAgainstDbAsync[TResult](TConnection conn, String sqltext, IDictionary`2 parameters, Func`3 dataReaderHandler, HttpContext httpCon
text, List`1 args)
      ClientConnectionId:3f9f4563-3a15-449a-a262-0a8838217224
      Error Number:208,State:1,Class:16
         --- End of inner exception stack trace ---
         at Azure.DataApiBuilder.Core.Resolvers.QueryExecutor`1.ExecuteQueryAgainstDbAsync[TResult](TConnection conn, String sqltext, IDictionary`2 parameters, Func`3 dataReaderHandler, HttpContext httpCon
text, List`1 args)
         at Azure.DataApiBuilder.Core.Resolvers.QueryExecutor`1.<>c__DisplayClass19_0`1.<<ExecuteQueryAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicat
es`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
         at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
         at Azure.DataApiBuilder.Core.Resolvers.QueryExecutor`1.ExecuteQueryAsync[TResult](String sqltext, IDictionary`2 parameters, Func`3 dataReaderHandler, HttpContext httpContext, List`1 args, String d
ataSourceName)
         at Azure.DataApiBuilder.Core.Services.SqlMetadataProvider`3.PopulateColumnDefinitionsWithReadOnlyFlag(String tableName, String schemaOrDatabaseName, SourceDefinition sourceDefinition)
         at Azure.DataApiBuilder.Core.Services.SqlMetadataProvider`3.PopulateSourceDefinitionAsync(String entityName, String schemaName, String tableName, SourceDefinition sourceDefinition, String[] runtim
eConfigKeyFields)
         at Azure.DataApiBuilder.Core.Services.SqlMetadataProvider`3.PopulateObjectDefinitionForEntities()
         at Azure.DataApiBuilder.Core.Services.SqlMetadataProvider`3.InitializeAsync()
         at Azure.DataApiBuilder.Service.Startup.PerformOnConfigChangeAsync(IApplicationBuilder app)
fail: Azure.DataApiBuilder.Service.Startup[0]
      Could not initialize the engine with the runtime config file: C:\Users\sample_user\dab-config.json
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
dab : Unable to launch the Data API builder engine.
At line:9 char:1
+ dab start --config "C:\Users\sample_user\dab-config.json"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unable to launc...builder engine.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Error: Failed to start the engine.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gamewizzzz**
## Why make this change?

- Resolves #1896

## What is this change?

- These changes impact API builder startup. The query output has not been modified, but certain field references are capitalized.
- The proper case is used to avoid "field not found" and "key field not found" errors when the database collation is case-sensitive.

## How was this tested?

- [x] Integration Tests - Ran locally; about 5 tests failed, but it was the same ones that failed before modifications
- [ ] Unit Tests

## Sample Request(s)
- N/A

### CODE REVIEW

**Comment by gamewizzzz** [comment]
@microsoft-github-policy-service agree

File: src/Core/Resolvers/DWSqlQueryBuilder.cs [hunk 1]
```diff
@@ -219,10 +219,10 @@ public string BuildStoredProcedureResultDetailsQuery(string databaseObjectName)
         public string BuildQueryToGetReadOnlyColumns(string schemaParamName, string tableParamName)
         {
             // For 'timestamp' columns sc.is_computed = 0.
-            string query = "SELECT ifsc.column_name from sys.columns as sc INNER JOIN INFORMATION_SCHEMA.COLUMNS as ifsc " +
-                "ON (sc.is_computed = 1 or ifsc.data_type = 'timestamp') " +
-                $"AND sc.object_id = object_id({schemaParamName}+'.'+{tableParamName}) and ifsc.table_name = {tableParamName} " +
-                $"AND ifsc.table_schema = {schemaParamName} and ifsc.column_name = sc.name;";
+            string query = "SELECT ifsc.COLUMN_NAME from sys.columns as sc INNER JOIN INFORMATION_SCHEMA.COLUMNS as ifsc " +
+                "ON ( sc.is_computed = 1 or ifsc.DATA_TYPE = 'timestamp' ) " +
```
Comment (seantleonard) [inline src/Core/Resolvers/DWSqlQueryBuilder.cs:223]:
```suggestion
                "ON (sc.is_computed = 1 or ifsc.DATA_TYPE = 'timestamp') " +
```

File: src/Core/Resolvers/MsSqlQueryBuilder.cs [hunk 2]
```diff
@@ -494,10 +494,10 @@ public string BuildStoredProcedureResultDetailsQuery(string databaseObjectName)
         public string BuildQueryToGetReadOnlyColumns(string schemaParamName, string tableParamName)
         {
             // For 'timestamp' columns sc.is_computed = 0.
-            string query = "SELECT ifsc.column_name from sys.columns as sc INNER JOIN information_schema.columns as ifsc " +
-                "ON (sc.is_computed = 1 or ifsc.data_type = 'timestamp') " +
-                $"AND sc.object_id = object_id({schemaParamName}+'.'+{tableParamName}) and ifsc.table_name = {tableParamName} " +
-                $"AND ifsc.table_schema = {schemaParamName} and ifsc.column_name = sc.name;";
+            string query = "SELECT ifsc.COLUMN_NAME from sys.columns as sc INNER JOIN INFORMATION_SCHEMA.COLUMNS as ifsc " +
+                "ON ( sc.is_computed = 1 or ifsc.DATA_TYPE = 'timestamp' ) " +
```
Comment (seantleonard) [inline src/Core/Resolvers/MsSqlQueryBuilder.cs:498]:
```suggestion
                "ON (sc.is_computed = 1 or ifsc.DATA_TYPE = 'timestamp') " +
```

File: src/Core/Resolvers/MsSqlQueryBuilder.cs [hunk 3]
```diff
@@ -494,10 +494,10 @@ public string BuildStoredProcedureResultDetailsQuery(string databaseObjectName)
...
+                $"AND sc.object_id = object_id({schemaParamName}+'.'+{tableParamName}) AND ifsc.TABLE_SCHEMA = {schemaParamName} " +
+				$"AND ifsc.TABLE_NAME = {tableParamName} AND ifsc.COLUMN_NAME = sc.name;";
```
Comment (seantleonard) [inline src/Core/Resolvers/MsSqlQueryBuilder.cs:500]:
```suggestion
                $"AND ifsc.TABLE_NAME = {tableParamName} AND ifsc.COLUMN_NAME = sc.name;";
```
dotnet format wants spaces and not tabs.

File: src/Core/Resolvers/DWSqlQueryBuilder.cs [hunk 4]
```diff
@@ -219,10 +219,10 @@ public string BuildStoredProcedureResultDetailsQuery(string databaseObjectName)
...
+                $"AND sc.object_id = object_id({schemaParamName}+'.'+{tableParamName}) AND ifsc.TABLE_SCHEMA = {schemaParamName} " +
+				$"AND ifsc.TABLE_NAME = {tableParamName} AND ifsc.COLUMN_NAME = sc.name;";
```
Comment (seantleonard) [inline src/Core/Resolvers/DWSqlQueryBuilder.cs:225]:
```suggestion
                $"AND ifsc.TABLE_NAME = {tableParamName} AND ifsc.COLUMN_NAME = sc.name;";
```
dotnet format wants spaces and not tabs.

**Review by seantleonard — COMMENTED** [review]
thank you for making these changes to enable compat with case sensitive db collations! few things to update then should be good to go.

**Comment by gamewizzzz** [comment]
Code change suggestions reviewed and accepted. Thanks for the heads up on the tab characters.

**Review by seantleonard — APPROVED** [review]
thanks for making these changes!

**Comment by gamewizzzz** [comment]
Most of the failed checks are showing "failed to connect to instance" error. I can't see further details since I don't have access to the azure pipeline pages. Is there something I needed to do with connection parameters? I made sure it wasn't included in commit.

**Comment by seantleonard** [comment]
> Most of the failed checks are showing "failed to connect to instance" error. I can't see further details since I don't have access to the azure pipeline pages. Is there something I needed to do with connection parameters? I made sure it wasn't included in commit.

@gamewizzzz Your changes are good. We're updating some pipeline logic and I'm looking into getting them working. Sorry for the delay.

**Review by Aniruddh25 — APPROVED** [review]

**Comment by Aniruddh25** [comment]
@gamewizzzz, the MySQL/PgSQL tests are failing since their query builders need to be updated as well. 

Could you please fix this: https://github.com/Azure/data-api-builder/blob/fa419cd46fe12d16633ce9bb317140c342d38183/src/Core/Resolvers/MySqlQueryBuilder.cs#L357

**Comment by EHekkert** [comment]
@gamewizzzz, are you still working on this?

**Comment by gamewizzzz** [comment]
No. Shortly after getting the test build to run successfully, one of the
other branches changed something to the point I could not upgrade the tool
properly on the test environment. Haven't had time to try again since.

**Comment by sander1095** [comment]
Hi @Aniruddh25 . Any help from the DAB team to finish this PR?

**Comment by Aniruddh25** [comment]
> Hi @Aniruddh25 . Any help from the DAB team to finish this PR?

@sander1095  - yes, we will take it forward and merge this.

File: src/Core/Resolvers/PostgresQueryBuilder.cs [hunk 5]
```diff
@@ -228,7 +228,7 @@ public string BuildStoredProcedureResultDetailsQuery(string databaseObjectName)
         /// <inheritdoc/>
         public string BuildQueryToGetReadOnlyColumns(string schemaParamName, string tableParamName)
         {
-            string query = "SELECT attname AS column_name FROM pg_attribute " +
+            string query = "SELECT attname AS \"COLUMN_NAME\" FROM pg_attribute " +
```
Comment (aaronburtle) [inline src/Core/Resolvers/PostgresQueryBuilder.cs:231]: Are quotes needed here? The other statements don't seem to make use of double quotes, for example
image

For style consistency would be better if we can remove these, or if quotes are needed see if single quote will work since we already use some single quotes in queries in this class.

**Comment by gamewizzzz** [comment]
The example you reference in "image.png" shows double quotes, I'm not sure
how that helps your argument.

Looking at line 231 where the quotes are used, I would say the quotes are
needed. In line 231, dynamic SQL syntax is being assigned to a string
variable so it can be passed as an argument to another command that
executes the SQL. That can't be done without at least one set of quotes
since you have spaces in the statement. The most you could do is combine
lines 231 and 232, but then again the code is broken out that way to help
with readability.

I agree with your point about the styling inconsistency of single quotes
(') vs double quotes ("). The inconsistency costs extra time in explaining
and transfering to other maintainers. However, there are legitimate reasons
to use one over the other in MS SQL queries:

   - Variable expansion. Double quotes allow you to pre-expand variables
   before assigning the result to the string, whereas single quotes you
   cannot. You may be able to get away with wrapping line 231 in single
   quotes, but line 232 you cannot because schemaParamName is being expanded
   - Flexibility of SQL syntax. Double quotes still allow you to embed
   single quotes in the SQL query without much headache. In line 232, a string
   literal is being referenced in the filter of the dynamic SQL, and is
   wrapped in single quotes. If you tried to use single quotes to wrap the
   whole statement, you will have to escape the single quotes of the literal.
   Once you start having to do escaped characters, it gets a little more
   difficult to work with them when debugging errors

**Comment by aaronburtle** [comment]
> The example you reference in "image.png" shows double quotes

I probably wasn't clear enough, but I am referencing the hard coded and escaped double quotes around `COLUMN_NAME`, typically if we are quoting parts of the sql statements we use a helper function, or leave the quotes out, or in some cases I think we have single quotes. Just want to align this with the rest of the code.

**Review by aaronburtle — APPROVED** [review]
LGTM!
